feat(rest/ui): Project vulnerability endpoint update & added new project rating in UI
eclipse/sw360 pull request #1025
Opened 2020-10-22 07:13 UTC by smrutis1

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

 Which issue is this pull request belonging to and how is it solving it? (#1024 )
 Did you add or update any new dependencies that are required for your change? - No

Issue:  closes #1024 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?

* Go to  Project-> Vulnerabilities, a new project rating `In Analysis` should be visible in the dropdown.
* Need to test project vulnerabilities endpoints as per the newly added documentation. 

Have you implemented any additional tests? - Yes, for REST documentation

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

2020-10-22 13:48 UTC, JaideepPalit requested changes
Reviewed and tested the PR.
Kindly look into some minor review comments and observations.

**Observations**
- request structure in PATCH API doc is not correct
- comment is not coming in response and doc for `get-project-vulnerability`
- Non-existing external Id and release ID gives 200 ok response in PATCH response

2020-10-23 08:01 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +import org.apache.http.HttpEntity;
Removed it

2020-10-23 08:02 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vulnerability/Sw360VulnerabilityService.java
> +        if (vulnerabilityCheckStatusHistory != null && vulnerabilityCheckStatusHistory.size() > 0) {
Used `isNotEmpty(_)` one

2020-10-23 08:04 UTC, smrutis1 commented
@JaideepPalit , Thanks for review and test. Have rectified the issues. Now if there is any invalid externalId or releaseId, it would return a `400 Bad Request` along with appropriate message.

2020-10-23 09:48 UTC, JaideepPalit commented
**Retested the PR and Observations**
> 
> * request structure in PATCH API doc is not correct 
      - looks fine
> * comment is not coming in response and doc for `get-project-vulnerability`
      - `working fine`
> * Non-existing external Id and release ID gives 200 ok response in PATCH response
      - `working fine`

**Issue**
Get request for new Project - `working fine`
Get request is not working after doing a patch - 500 error, message - null
```
2020-10-23 09:08:04 ERROR ProcessFunction:47 - Internal error processing getVulnerabilitiesByProjectId
org.eclipse.sw360.datahandler.thrift.SW360Exception: null
    at org.eclipse.sw360.datahandler.common.SW360Assert.fail(SW360Assert.java:134) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotNull(SW360Assert.java:42) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.common.SW360Assert.assertNotNull(SW360Assert.java:36) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.db.ProjectDatabaseHandler.getProjectById(ProjectDatabaseHandler.java:256) ~[src-common-11.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.vulnerabilities.VulnerabilityHandler.getVulnerabilitiesByProjectId(VulnerabilityHandler.java:92) ~[src-vulnerabilities-11.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.thrift.vulnerabilities.VulnerabilityService$Processor$getVulnerabilitiesByProjectId.getResult(VulnerabilityService.java:1506) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
    at org.eclipse.sw360.datahandler.thrift.vulnerabilities.VulnerabilityService$Processor$getVulnerabilitiesByProjectId.getResult(VulnerabilityService.java:1486) ~[datahandler-11.1.0-SNAPSHOT.jar:?]
    at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [libthrift-0.13.0.jar:0.13.0]
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [libthrift-0.13.0.jar:0.13.0]
```

2020-10-23 11:00 UTC, smrutis1 commented
Rebased and fixed the reported issue.

2020-10-23 11:22 UTC, JaideepPalit approved these changes
Code looks fine to me.
Tested successfully.

2020-10-23 11:37 UTC, merged