feat(rest): New search resource endpoint and get releases for multiple projects
eclipse/sw360 pull request #1030
Opened 2020-10-30 08:04 UTC by smrutis1

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

Added two new endpoints viz. to search resources using `api/search?searchText=376570&typeMasks=project` and to get releases using multiple project ids. `/projects/releases?clearingState=APPROVED` and added pagination support to the later one along with the get all releases endpoint.

Issue: 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

Need to test newly created rest endpoints as mentioned in the documentation.

> Have you implemented any additional tests? 

 Yes, for REST documentation

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

2020-10-30 12:01 UTC, JaideepPalit requested changes
Reviewed the PR - Kindly look into some review comments.

2020-11-03 04:41 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
> +        embeddedRelease.setId(release.getId());
reused

2020-11-03 04:45 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/search/SearchController.java
> +    public ResponseEntity<Resources<Resource<SearchResult>>> getSearchResult(@RequestParam(value = "searchText") String searchText, @RequestParam Optional<List<String>> typeMasks) throws TException {
added

2020-11-03 04:47 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> +                 .param("transitive", "false")
Added the request statement

2020-11-03 04:49 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java
> +        ExecutorService  exeService = Executors.newCachedThreadPool();
Have used fixed thread pool and made it static

2020-11-03 04:53 UTC, smrutis1 commented
@JaideepPalit , Thanks for review. Have incorporated the review comments.

2020-11-05 07:01 UTC, JaideepPalit requested changes
Tested the PR. Some Observations.
- Search with project , component, release , license, vendor - `working fine `
- Get project releases based on clearing state - `working fine`


- Search with user and obligation is not working, always 204 No content is coming.
- Exception is coming at tomcat startup
```
2020-11-05 06:23:40.249 ERROR [Framework Event Dispatcher: Equinox Container: 0dd3384e-20bb-4cdb-ad33-690b20cf17de][Framework:93] FrameworkEvent ERROR 
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at org.apache.aries.component.dsl.OSGi.lambda$null$79(OSGi.java:734)
	at org.apache.aries.component.dsl.internal.JustOSGiImpl.lambda$new$2(JustOSGiImpl.java:47)
	at org.apache.aries.component.dsl.internal.OSGiImpl.run(OSGiImpl.java:50)
	at org.apache.aries.component.dsl.OSGi.lambda$null$80(OSGi.java:732)
	at org.apache.aries.component.dsl.OSGi.lambda$null$64(OSGi.java:602)
	at org.apache.aries.component.dsl.Publisher.apply(Publisher.java:28)
	at org.apache.aries.component.dsl.OSGi.lambda$null$66(OSGi.java:663)
	at org.apache.aries.component.dsl.Publisher.apply(Publisher.java:28)
```

- Exception is coming at tomcat shutdown.

```
Exception in thread "pool-147-thread-1" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/ParameterizedMessage
	at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:104)
	at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:75)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2010)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:793)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:76)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.message.ParameterizedMessage]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1375)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
	... 7 more
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.message.ParameterizedMessage]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
	... 9 more
Exception in thread "pool-148-thread-1" Exception in thread "pool-142-thread-1" Exception in thread "pool-144-thread-1" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/ParameterizedMessage
	at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:104)
	at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:75)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2010)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:793)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:76)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.logging.log4j.message.ParameterizedMessage]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1375)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
	... 7 more

```

2020-11-05 09:17 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java
> +    public Release convertToEmbeddedReleaseWithDet(Release release) {
Done

2020-11-05 09:26 UTC, smrutis1 commented
> * Search with user and obligation is not working, always 204 No content is coming.

May be need to test it where the user and obligation search is working in UI as there is no change in rest except calling the backend service and giving the response back.

> * Exception is coming at tomcat startup
>

Unfortunately I am not able to reproduce the issue. 

> 
> * Exception is coming at tomcat shutdown.
> 


I have been seeing this for other branches as well. May be not due to the changes in this PR

2020-11-05 12:26 UTC, JaideepPalit commented
Deployed on test instance and Retested the PR.

> * Exception is coming at tomcat startup
>    - Exception is not appearing in test instance

> * Exception is coming at tomcat shutdown
>    - Similar exception is coming in separate branch in test instance. Could be related to some other issue.

> * Search with user and obligation is not working, always 204 No content is coming.
>   - Search with user is `working` in test instance.
>   - Search with obligation is `not working` in test instance.

2020-11-06 09:10 UTC, JaideepPalit commented
(from discussion) - Created separate issue #1035 for search with Obligation

2020-11-06 09:11 UTC, JaideepPalit approved these changes

2020-11-06 09:11 UTC, merged