feat(ProjectListUI): Added clearing state filter in Project List
eclipse/sw360 pull request #1032
Opened 2020-11-03 12:27 UTC by JaideepPalit

> Added clearing state filter in Project List
> * Which issue is this pull request belonging to and how is it solving it? (*#1031*)
> * Did you add or update any new dependencies that are required for your change? - No

### How To Test?
> Search with Project Clearing state in Project List UI
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2020-11-05 04:34 UTC, smrutis1 requested changes
Observed an issue while testing,

Searching with some entry in the clearing state filter field works fine. However after hitting the search button post resetting the filed value to blank/no-content, then there is no result. Ideally it should show the list of projects.

2020-11-05 04:34 UTC, smrutis1 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectSearchHandler.java
> +                    "    if(doc.clearingState !== undefined && doc.clearingState != null && doc.clearingState.length >0) {  "+
May be It can simply be written as `if(doc.clearingState)`

2020-11-05 10:38 UTC, JaideepPalit commented
Thanks for review and test.
Made changes and fixed the issue

2020-11-06 06:52 UTC, smrutis1 approved these changes

2020-11-06 06:53 UTC, smrutis1 commented
Tested successfully

2020-11-06 06:53 UTC, merged