feat(CR-UI): Added Advaced filter for CR & fix # of components count
eclipse/sw360 pull request #1037
Opened 2020-11-10 08:09 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
 * Added `Advanced Filter` for `Clearing Request`, based on `Priority`, `BA/BL` and `Status`.
 * Did you add or update any new dependencies that are required for your change? - **No**

Issue: #1036 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
* Test the advanced filter are for CR are working fine.
* Check the `# of components to be cleared` shows the number of releases in with clearing 
* Have you implemented any additional tests? - **No**

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Abdul Kapti <abdul.mannankapti@siemens.com>

2020-11-10 09:10 UTC, akapti commented
Screenshot:
![image](https://user-images.githubusercontent.com/50870174/98653098-9811c280-2362-11eb-9557-543fcd7dbff9.png)

2020-11-10 09:20 UTC, mcjaeger commented
(from dicussion) two proposals:

* Progress with capital P
* pls consider renaming business line with group

2020-11-17 13:02 UTC, smrutis1 requested changes
Reviewed and tested:

* It's working fine after adding custom field(BA BL) in control panel.

* It's not working without adding `custom field 'BA BL'` in control panel.
![image](https://user-images.githubusercontent.com/46560890/99393045-bfd4cd80-2902-11eb-94a7-2d70184d23b4.png)

2020-11-18 10:52 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
> +                            $(this).hide().attr("disabled", "");
Changes done.

2020-11-18 10:57 UTC, akapti commented
> Reviewed and tested:
It's not working without adding custom field 'BA BL' in control panel.

Fixed the above mentioned issue.

2020-11-19 11:05 UTC, smrutis1 approved these changes
Code looks good. Tested successfully.

2020-11-19 11:07 UTC, merged