feat(projectEdit): Project creators and moderators can edit few fields in a closed project
eclipse/sw360 pull request #1045
Opened 2020-11-17 08:24 UTC by smrutis1

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? 

Closes: #1044 

> * Did you add or update any new dependencies that are required for your change? - 

No

Issue:  #1044 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

Add some user as moderator to a project. Make the project clearing state to closed. Login with user which is added as a moderator and edit the project. All fields should be disabled except editing external id, security vulnerability monitoring and security vulnerabilities display
> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

2020-11-18 12:32 UTC, akapti requested changes
Tested the PR, and found following issues.

1. The `edit` button on project list page is still disabled for project creator and moderators.
2. `Security Vulnerability Monitoring` field is still disabled for non-admin users.
3. Modifying `External Id`, `Security Vulnerability Monitoring` and `Security Vulnerabilities Display` by project creator (or user with non-Admin role) is not being saved.
4. Project creator is getting added as `Moderator` whenever project is being saved (updated)

2020-11-19 08:34 UTC, smrutis1 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
> +    private boolean isModeratorOrCreator(Project project, User user) {
Moved it to `SW360Utils`

2020-11-19 08:34 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/administrationEdit.jspf
> +<core_rt:set var="clearingStateClosedNUserNotAdmin" value="${(project.clearingState eq 'CLOSED') && (isUserAdmin != 'Yes')}"/>
Done

2020-11-19 08:36 UTC, smrutis1 commented
Thanks for review and test. Have fixed the issues and regarding mentioned issue in 2nd point, the field will be enabled only when there is entries in the `Security Responsibles` filed.

2020-11-19 13:28 UTC, akapti commented
Code looks good.
tested the PR, and is working as expected.

2020-11-19 13:46 UTC, akapti reviewed
Code looks good.
Tested the PR. Working as expected from UI. 
But Non-Admin user (creator & moderator) don't have `write` access to project via `REST` API.

2020-11-20 04:43 UTC, smrutis1 commented
@akapti , Please make sure `rest.write.access.usergroup=USER` is set in sw360.properties

2020-11-20 05:58 UTC, akapti approved these changes

2020-11-20 09:17 UTC, merged