feat(ChangeLogs): Fixed issue related to null to empty string or collection conversion
eclipse/sw360 pull request #1054
Opened 2020-11-26 08:55 UTC by JaideepPalit

> Fixed issue related to null to empty string or collection conversion
> * Which issue is this pull request belonging to and how is it solving it? (*#1053*)
> * Did you add or update any new dependencies that are required for your change?

### How To Test?
> Update/Create Project component release. Conversions like null to `"", {}, []` or vice-versa should not be shown to user
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2020-12-04 09:10 UTC, mcjaeger approved these changes

2020-12-04 09:10 UTC, mcjaeger commented
(code has some formatting issues)

2020-12-04 09:14 UTC, mcjaeger requested changes
please a. not three quals, b. spaces

2020-12-04 09:20 UTC, mcjaeger commented
(from discussion) pro and cons about having the changelog here and there, maybe, if the changelog is delivered over the REST API, maybe it is better to move it into the backend level

2020-12-08 07:42 UTC, JaideepPalit commented
Made changes as suggested.
Moved code to backend.

2020-12-09 21:58 UTC, mcjaeger commented
re-test looks good

2020-12-09 22:01 UTC, mcjaeger commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ChangeLogsDatabaseHandler.java
> +            .add("documentState").build();
maybe ìssetBitfield`might com ein future or whatever its name is

2020-12-09 22:02 UTC, mcjaeger approved these changes
code looks OK to me (at least)

2020-12-09 22:02 UTC, merged