fix(rest): Fixed update Project API issue - unexpected changes in some fields like moderators ,contributors, etc
eclipse/sw360 pull request #1058
Opened 2020-12-01 07:19 UTC by JaideepPalit

> Fixed update Project API issue - unexpected changes in some fields like moderators ,contributors, etc
> * Which issue is this pull request belonging to and how is it solving it? (*#1057*)
> * Did you add or update any new dependencies that are required for your change? - No

### How To Test?
> How should these changes be tested by the reviewer? - Refer #1057 
> Have you implemented any additional tests? - Yes, Testcase for Doc

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2020-12-02 06:36 UTC, smrutis1 requested changes
Tested this PR. 

Observed one issue like after firing a REST patch request, the response contains `sw360:projects` tag, generally this should contain the self detail as per the documentaion. Unfortunately it is containing the project details of linked project.

2020-12-02 06:36 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +    @NonNull()
Please remove the empty parenthesis.

2020-12-02 06:36 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java
> +        ObjectMapper mapper = new ObjectMapper(); // jackson's objectmapper
would be good to remove the commented message.

2020-12-02 11:16 UTC, JaideepPalit commented
Thanks for review and test.
Made changes as per review comments.

>Observed one issue like after firing a REST patch request, the response contains sw360:projects tag, generally this should contain the self detail as per the documentaion. Unfortunately it is containing the project details of linked project.

 - Fixed Documentation. `sw360:projects` is for linked Projects similar like in GetProjectByID.
The Main Doc contains project details and self link is provided in `"_links" ->"self"`

2020-12-04 04:11 UTC, smrutis1 approved these changes
Code looks good. Tested successfully

2020-12-04 09:07 UTC, merged