feat(SplitComponent): Add tooltip for releases of component with SourceCodeDownloadUrl and BinaryDownloadUrl during split feature
eclipse/sw360 pull request #1067
Opened 2020-12-10 08:34 UTC by JaideepPalit

> Add tooltip for releases of component with SourceCodeDownloadUrl and BinaryDownloadUrl during split feature
> * Which issue is this pull request belonging to and how is it solving it? (*#1066*)
> * Did you add or update any new dependencies that are required for your change? - No

### How To Test?
> Split Component with releases and attachments . Check tooltip of individual releases should show respective `SourceCodeDownloadUrl and BinaryDownloadUrl`
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2020-12-10 12:09 UTC, smrutis1 approved these changes
Code looks good. Tested successfully as per the mentioned steps.

2020-12-10 14:17 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/splitComponent.jsp
> +            return 'Source Code Download Url - ' + (release.sourceCodeDownloadurl || '') + '\n' + 'Binary Download Url - ' + (release.binaryDownloadurl || '');
Is it possible to read `Source Code Download Url` and `Binary Download Url` from language properties file.

2020-12-10 14:19 UTC, smrutis1 requested changes
Just a minor comment

2020-12-10 14:45 UTC, JaideepPalit commented
Thanks for review and test.
Reading `Source Code Download Url` and `Binary Download Url` from language properties file

2020-12-11 06:53 UTC, smrutis1 approved these changes
Code looks good. Tested again successfully.

2020-12-11 09:56 UTC, merged