feat(rest): Added endpoint to get changelog by document id
eclipse/sw360 pull request #1089
Opened 2021-01-12 05:38 UTC by JaideepPalit

>  Added endpoint to get changelog by document id
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change? - No

### How To Test? - Refer Rest Documentation `3.12.1. Get changelog by document id`
> How should these changes be tested by the reviewer?
   - Execute Endpoint `/api/changelog/document/{docId}?page=0&page_entries=5&sort=changeTimestamp%2Casc` with pagination parameter
> Have you implemented any additional tests?

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2021-01-20 08:00 UTC, smrutis1 requested changes
Few Observations:

* Please add about change log in section `3. Resources` of documentation.
* In pagination field description please add appropriate field description instead of search results. ref: 
![image](https://user-images.githubusercontent.com/46560890/105144420-3bc9dc80-5b23-11eb-80d5-562c08ed5dbd.png)


This endpoint provides list of changelogs of a document. Similarly I think another endpoint would be good to fetch individual changelog by using  changelog id.

2021-01-21 07:44 UTC, JaideepPalit commented
Thanks for review and test.
Made changes as suggested.

2021-01-22 06:59 UTC, smrutis1 requested changes
Seems like in HAL browser the highlighted link in red gives an `404` response. and doc link here is also seems to be not working.

![image](https://user-images.githubusercontent.com/46560890/105456992-1fa57700-5cac-11eb-8e57-1d25a1155dc3.png)

![image](https://user-images.githubusercontent.com/46560890/105457371-bb36e780-5cac-11eb-8c2b-f11f4d3f2c63.png)

2021-01-22 06:59 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ChangeLogSpecTest.java
> +                                fieldWithPath("page.size").description("Number of search results per page"),
Please update search results to changelogs here and in below line too

2021-01-22 11:32 UTC, JaideepPalit commented
Added fix for above comment

2021-01-22 13:13 UTC, smrutis1 approved these changes
Code looks good to me. Tested successfully.

2021-01-22 13:14 UTC, merged