fix(excelexport): Projects with linked releases excel export error
eclipse/sw360 pull request #1106
Opened 2021-02-03 07:53 UTC by smrutis1

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Did you add or update any new dependencies that are required for your change? - No

Sometime if due to some reason, the release reference is present in project document, how ever it is not actually available in DB, then the whole export is not working. In this PR, fixed the null pointer and added a message like "Release not available" in the columns of excel report corresponding to the release fields.

### How To Test?
> How should these changes be tested by the reviewer?

Please refer the description.

> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

2021-02-11 07:00 UTC, JaideepPalit requested changes
Tested the PR. Seems to be some issue.
Test Steps done
1. Create New Project with Linked Releases and Projects
2. Goto DB update Release Id to something non-existent
3. Goto Project List Tab. Export Excel with/without linked releases. 
    - Observation - Project doesnot open .  Getting 500 - NullPointerException while Export excel
4. Perform same steps from 1-3 for Linked Projects. Same Error occurs
5. Perform same steps from 1-3 for New Release with linked Release. 
    - Observation - Release opens. Export works but with no error messages in excel

Error Logs - 
[ProjectLinkedProject.txt](https://github.com/eclipse/sw360/files/5963494/ProjectLinkedProject.txt)
[ProjectLinkedRelease.txt](https://github.com/eclipse/sw360/files/5963495/ProjectLinkedRelease.txt)

2021-02-11 13:25 UTC, smrutis1 commented
@JaideepPalit Thanks for test and sharing log messages. Have added logic to handle corrupted linked ids. 

> 4. Perform same steps from 1-3 for Linked Projects. Same Error occurs

Export should work now if linked project id is corrupted. However the project won't open with a default behavior with error message like `Error fetching project. Project or its dependencies are not found` 

> 5. Perform same steps from 1-3 for New Release with linked Release.
>    
>    * Observation - Release opens. Export works but with no error messages in excel
> 

Just gave a try in my local machine, looks like linked releases of release is not part of project export, hence the corresponding error message is also not part of excel.

2021-02-11 13:46 UTC, JaideepPalit commented
> Just gave a try in my local machine, looks like linked releases of release is not part of project export, hence the corresponding error message is also not part of excel.
   - In order to test , for corrupt linked release of a release. Please use Export Excel from Components tab.

2021-02-12 05:12 UTC, smrutis1 commented
components tab excel export also seems to be not containing linked releases. Please let me know if I am missing something.

2021-02-12 07:10 UTC, JaideepPalit commented
> components tab excel export also seems to be not containing linked releases. Please let me know if I am missing something.
  - Not sure. May be this is not part of this PR. In the excel sheet , there are two columns `release with relationship` for release and `linked Project` for Project. The value of that cell skips the Release Id/Project Id missing and no message like `Release Id/Project Id : Release/Project not available`.
![image](https://user-images.githubusercontent.com/56534710/107739559-236a6d80-6d2f-11eb-9d84-35b860e4de46.png)

2021-02-12 07:12 UTC, JaideepPalit approved these changes
Code looks fine to me. Tested successfully Excel download of Project for missing Release id and Project Id.

2021-02-14 23:35 UTC, merged