feat(PredefinedTags):Predefined tags per group in the Projects Tag field.
eclipse/sw360 pull request #1142
Opened 2021-03-15 15:14 UTC by ravi110336

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
     - created the new predefined tags for the Tag field in the Projects.

> * Which issue is this pull request belonging to and how is it solving it? (#1141 )
> * Did you add or update any new dependencies that are required for your change? No

Issue: 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
  - Add a project in SW360 and select the tag from the auto-populated tag values.
  -  we can also write our own tag as per the group if the tag is not present in the sw360.properties.
  
![image](https://user-images.githubusercontent.com/56516845/111175105-1363d900-85ce-11eb-9076-20774e8878ad.png)

> Have you implemented any additional tests? 
No

### Checklist
Must:
- [] All related issues are referenced in commit messages and in PR

Signed-off-by: Ravindra Kumar kumar.ravindra@siemens.com

2021-03-25 08:15 UTC, JaideepPalit requested changes
Reviewed and tested the PR.
Kindly look into some minor review comments.
Tested the PR. Popup and tags are not appearing. Getting console error.
![image](https://user-images.githubusercontent.com/56534710/112440468-5cefb900-8d70-11eb-8eaf-21c0894ab5d8.png)

2021-04-01 07:32 UTC, ravi110336 commented on frontend/sw360-portlet/src/main/resources/sw360.properties
> +predefined.tags=["WIP","WIN_TS","mep","W4D","VC10A SC2000 USD 6.0","V@RENA","TSS","TCO","SY","STT30","SRSNG","SMO","SLN","SIT_Perf","SI RSS-EU","SI RSS-DE","SI RSS SSP DES","SI LP NA R&D EL","SI LP",
Removed these values from the sw360 properties , need to give these values during deployment.

2021-04-01 07:33 UTC, ravi110336 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/basicInfo.jspf
> +</style>
created the new css file separately for the autocomplete, which can be used for the future enhancement.

2021-04-01 08:07 UTC, JaideepPalit approved these changes
Code looks fine to me.
Tested successfully

2021-04-01 08:31 UTC, merged