feat(couchdb-java-client): Migrating from ektorp to cloudant
eclipse/sw360 pull request #1149
Opened 2021-03-17 09:29 UTC by smrutis1

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*#1148*)
> * Did you add or update any new dependencies that are required for your change? - Yes

Have added a new library(cloudant java client) instead of ektorp for DB operations.

Issue: Closes #1148 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
Need to 
> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

2021-04-15 21:41 UTC, mcjaeger commented
test run cleanly on vagrant (Java 11 based, Ubuntu 20, Couchdb 311)

2021-04-22 08:15 UTC, JaideepPalit requested changes
Reviewed the PR.
Kindly have a look at the review comments.

2021-04-22 08:15 UTC, JaideepPalit commented on libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/DatabaseSettings.java
> +
Add log.error()

2021-04-22 08:15 UTC, JaideepPalit commented on libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/AttachmentConnector.java
>  import org.eclipse.sw360.datahandler.thrift.attachments.Attachment;
Remove used imports
```
import org.ektorp.http.HttpClient;
import java.util.HashSet;
```

2021-04-22 08:15 UTC, JaideepPalit commented on libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/common/DatabaseSettingsTest.java
> +
Good to have log.error()

2021-04-22 08:15 UTC, JaideepPalit commented on libraries/lib-datahandler/src/test/java/org/eclipse/sw360/datahandler/couchdb/AttachmentStreamConnectorTest.java
>  import com.fasterxml.jackson.annotation.JsonAutoDetect;
remove unused import

2021-04-22 08:59 UTC, ravi110336 commented
Tested the UI and it is working fine for most of the cases but found some below issue, Please check:

Issue 1:
    Add release to  a component and while fetching the release details getting the error message " Error:Error fetching release from backend."
![image](https://user-images.githubusercontent.com/56516845/115686010-66bc0a80-a376-11eb-85d9-fc7f1dc47289.png)

Issue 2:
    Similar issue from  Admin->DataBaseSanitation->Releases with more than one source attachment:
     getting the error message " Error:Error fetching release from backend."

Issue 3:
    ECC-> click on release.  getting the error message " Error:Error fetching release from backend."

Observation 1: (Not sure if this is an issue )
Go to Requests -> click on any request -> blank result no output.
![image](https://user-images.githubusercontent.com/56516845/115686494-df22cb80-a376-11eb-9998-4668063bf728.png)

2021-04-23 04:20 UTC, smrutis1 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
>              throw new SW360Exception("Some of the usage documents could not be created: " + results);
Have validated the response/results before exception

2021-04-23 04:21 UTC, smrutis1 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/AttachmentDatabaseHandler.java
> +        List<Response> results = attachmentUsageRepository.executeBulk(attachmentUsages);
Have added the validation

2021-04-23 04:22 UTC, smrutis1 commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectVulnerabilityRatingRepository.java
> +//            log.error("More than one projectVulnerabilityRating found for project with id " + projectId);
Have added the logger

2021-04-23 04:23 UTC, smrutis1 commented on backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
> +        final List<Response> documentOperationResults = licenseTypeRepository.executeBulk(licenseTypes);
Have added the validation

2021-04-23 05:34 UTC, smrutis1 commented on backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationRequestRepository.java
>      @View(name = "documents", map = DOCUMENTS_VIEW)
Removed it

2021-04-23 05:46 UTC, smrutis1 commented on .travis.yml
> +    # Create couchdb.properties in /etc/sw360
In `DatabaseHandlerUtil.java` the changelog repository is being created in a static way. Hence the initialization of it fails without credentials and DB name in prop. file. (Ref1 https://github.com/eclipse/sw360/blob/4bf2932ba060384f5cd6975ef0e1fac78692dca8/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java#L94   Ref: https://github.com/eclipse/sw360/blob/4bf2932ba060384f5cd6975ef0e1fac78692dca8/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java#L316)

May be the construction of DatabaseHandlerUtil needs to changed to handle it properly. Let me know if it should be fixed here.

2021-04-23 05:55 UTC, smrutis1 commented
@JaideepPalit , Thanks for the review. Have incorporated most of them. Kindly have a look and let me know. @ravi110336 Thanks for the test. Have fixed the mentioned issues however the observation regarding "Request" tab, I am not able to reproduce it.

2021-04-30 07:10 UTC, smrutis1 commented on .travis.yml
> +    # Create couchdb.properties in /etc/sw360
From discussion, have handled it here.

2021-04-30 07:12 UTC, smrutis1 commented
@ravi110336 , From discussion, have rectified the issue with moderation request. Kindly have a look

2021-04-30 07:41 UTC, ravi110336 commented
Tested the moderation request and attachment download working fine.

2021-04-30 08:21 UTC, mcjaeger commented
tested also with vagrant: looks good

2021-04-30 10:08 UTC, JaideepPalit requested changes
**Re-reviewed the PR.**
Kindly have a look at some very minor comments.

**Note-** 
The travis-ci logs gives lot of error messages during test, which are not coming in other branches.
https://travis-ci.org/github/eclipse/sw360/jobs/768972323#L2046
```
Apr 30, 2021 6:56:28 AM com.cloudant.client.org.lightcouch.CouchDbClient createDB
INFO: Created Database: 'sw360_test_db'
2021-04-30 06:56:28 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/AttachmentUsage : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/AttachmentUsage. Error: not_found. Reason: missing.
2021-04-30 06:56:28 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/Attachment : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/Attachment. Error: not_found. Reason: missing.
2021-04-30 06:56:28 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/Source : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/Source. Error: not_found. Reason: missing.
2021-04-30 06:56:28 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/Vendor : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/Vendor. Error: not_found. Reason: missing.
2021-04-30 06:56:28 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/Release : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/Release. Error: not_found. Reason: missing.
2021-04-30 06:56:29 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/Component : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/Component. Error: not_found. Reason: missing.
2021-04-30 06:56:29 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/Project : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/Project. Error: not_found. Reason: missing.
2021-04-30 06:56:29 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/User : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/User. Error: not_found. Reason: missing.
2021-04-30 06:56:29 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id _design/ProjectVulnerabilityRating : 404 Object Not Found at http://localhost:5984/sw360_test_db/_design/ProjectVulnerabilityRating. Error: not_found. Reason: missing.
2021-04-30 06:56:29 ERROR DatabaseConnectorCloudant:138 - Error fetching document of type DesignDocument with id 
```
Seems like , using cloudant - design docs are not getting generated. 
It should also be tested on a clean system with no DBs or Design docs

2021-04-30 13:44 UTC, ravi110336 commented
I have tested the branch after deleting all the DBs and design docs in my local system, all the DBs are getting created with the design docs successfully.

2021-05-06 09:25 UTC, smrutis1 commented
@JaideepPalit Thanks for review. Have incorporated changes.
> **Note-**
> The travis-ci logs gives lot of error messages during test, which are not coming in other branches.
> https://travis-ci.org/github/eclipse/sw360/jobs/768972323#L2046

(from discussion): This is due to added logger message, it's ok to keep it.
* Have added the paginated view for components to mitigate loading issue

2021-05-07 07:35 UTC, JaideepPalit requested changes
Reviewed the PR.
Kindly have a look at some review comments.
Also seems to be some issue with 
 1. sorting based on vendor and main licenses 
     - case-sensitivity
     - Multivalue list
![sort1](https://user-images.githubusercontent.com/56534710/117414515-d7e1ed00-af34-11eb-8246-490c409576a0.JPG)

 2. There seems to some issue with pagination. Based on columns sorted like vendor/license/name - total result seems to vary
![comp_name](https://user-images.githubusercontent.com/56534710/117414086-5e49ff00-af34-11eb-9f59-9bb0d3bb11cf.JPG)
![main_lic](https://user-images.githubusercontent.com/56534710/117414103-630eb300-af34-11eb-84ca-bea545c1d43f.JPG)

2021-05-07 12:42 UTC, smrutis1 commented
> Reviewed the PR.
> Kindly have a look at some review comments.
> Also seems to be some issue with
> 
> 1. sorting based on vendor and main licenses
>    
>    * case-sensitivity
>    * Multivalue list\

(from discussion) Raised an issue #1199 
>     
> 2. There seems to some issue with pagination. Based on columns sorted like vendor/license/name - total result seems to vary
>    ![comp_name](https://user-images.githubusercontent.com/56534710/117414086-5e49ff00-af34-11eb-9f59-9bb0d3bb11cf.JPG)
>    ![main_lic](https://user-images.githubusercontent.com/56534710/117414103-630eb300-af34-11eb-84ca-bea545c1d43f.JPG)

Fixed it.

2021-05-07 12:47 UTC, JaideepPalit approved these changes
Code looks fine to me.

2021-05-07 13:07 UTC, mcjaeger commented
has been tested on our staging server, vagrant of course and again staging server....

2021-05-07 13:07 UTC, merged