fix(rest): Added support for pagination and retrival using multi value `projectRelevance` param
eclipse/sw360 pull request #1162
Opened 2021-03-25 08:51 UTC by smrutis1

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*#1160*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: CLoses #1160 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

Need to test the `projects/{id}/vulnerabilities?projectRelevance=APPLICABLE&projectRelevance=IRRELEVANT` endpoint(may be along with other filters) and verify the outputs if it works fine. 
Need to test the pagination as well. 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

2021-04-15 14:07 UTC, JaideepPalit requested changes
Kindly look into some minor review comments
Tested the PR on stage.
The REST API, fetches data properly for single/multi-value project-relevance and priority

However seems to be some issue with Pagination and sort.
1.	Response contains noVulnerability data for pagination
2.	totalPages and totalElements always shows 20 record. It should be no. of records found based on params
3.	Also tried sort without pagination, doesnot return sorted result

Shared more detailed info in mail.

2021-04-15 18:44 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> +                                parameterWithName("page").description("Page of releases"),
updated it to `vulnerabilities`

2021-04-15 18:45 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> +                                parameterWithName("sort").description("Defines order of the vulnerability")
Mentioned the options

2021-04-16 05:48 UTC, smrutis1 commented
@JaideepPalit , Thanks for review and test. Have fixed the mentioned issue, kindly have a look. 

And as discussed regarding the 3rd point, as the sorting and paging tightly coupled. Need to be discussed whether to include this as part of this PR or not as the same will be applicable for other endpoints where pagination has been applied

2021-04-16 07:15 UTC, JaideepPalit commented
Retested the PR.
1. Response contains noVulnerability data for pagination  - `working fine`
2. totalPages and totalElements always shows 20 record. It should be no. of records found based on params - `working fine`
3. Also tried sort without pagination, doesnot return sorted result - `issue persists`
4. sort with pagination - `works fine`

2021-04-16 08:15 UTC, JaideepPalit approved these changes

2021-04-16 08:16 UTC, merged