feat(VirusScanSchedulerService): Manual Scheduler service for deleting the attachment.
eclipse/sw360 pull request #1184
Opened 2021-04-23 11:21 UTC by ravi110336

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
    

- The manual scheduler service "**Delete Attachment from Local FileSystem**" will allow the user to delete the attachment which has been uploaded to local file system for virus scan which is more than 30 days older.

> * Which issue is this pull request belonging to and how is it solving it? (#1183  )
> * Did you add or update any new dependencies that are required for your change? No

Issue: 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

-  Check if there is attachment stored to local file system in the directory **/opt/sw360tempattachments**.
-  If no attachment present in local FS then upload attachment and update the project,component or release that should create the attachment in local FS.
-  If the attachment which is present is more than 30 days older then it should delete that attachment by clicking the Manual scheduler service from the Admin tab.
- If there is some attachment which is modified today but there exists some additional attachment which is more than 30 days older in this scenario only the attachment with 30 days older should get deleted.
- If in the directory all the attachment is more than 30 days older then it should delete the attachment along with the directory.

> Have you implemented any additional tests?

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: ravi110336 kumar.ravindra@siemens.com

2021-04-30 09:31 UTC, JaideepPalit commented
(from discussion): Manual trigger is already there. Scheduled based trigger needs to be implemented which runs automatically after certain interval of time.

2021-05-10 06:13 UTC, ravi110336 commented
Added the scheduler service to schedule the task for deletion of attachment in local FS, along with the manual deletion, also added the CVESearch for Manual deletion.

2021-06-02 18:48 UTC, JaideepPalit requested changes
Reviewed the PR.
Kindly have a look at some review comments

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
> +            log.warn("Unable to delete attachment. ", e);
Maybe it could be log.error since it returns `RequestStatus.FAILURE`

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src/src-schedule/src/main/java/org/eclipse/sw360/schedule/timer/ScheduleConstants.java
> +    public static final String DELETE_ATTACHMENT_OFFSET_DEFAULT  = 0 + "" ; // default 00:00 am, in seconds
Maybe it could be directly written as `"0"`

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src/src-schedule/src/main/java/org/eclipse/sw360/schedule/timer/ScheduleConstants.java
> +    public static final String DELETE_ATTACHMENT_INTERVAL_DEFAULT  = (24*60*60)+"" ; // default 24h, in seconds
Indentation `(24*60*60)+""`

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src/src-schedule/src/main/java/org/eclipse/sw360/schedule/timer/ScheduleConstants.java
> +            log.info("Property "+ DELETE_ATTACHMENT_OFFSET_PROPERTY_NAME + " not set. Using default value.");
Maybe log could be `debug` since it check for a property and uses default value if not present.
Indentation `"Property "+`
Same for Line 86-87

2021-06-02 18:48 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/ScheduleAdminPortlet.java
> +            log.error(e);
It would be good to have some Error message describing the error along with Exception stacktrace.
Same for line 184, 174, 162

2021-06-02 18:48 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/scheduleAdmin/view.jsp
> +                    <td>${deleteAttachmentNextSync}</td>
Kindly use `<sw360:out>` tag to display text in jsp. It prevents xml error

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
> +import java.net.MalformedURLException;
Kindly remove unused imports

2021-06-02 18:48 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/scheduleAdmin/view.jsp
> +</portlet:actionURL>
Kindly remove duplicate `portlet:actionURL` 
Line 34-35
Line43-44

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
> +                    boolean isFolderEmpty =  !stream.iterator().hasNext();
Kindly check Indentation

2021-06-02 18:48 UTC, JaideepPalit commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
> +        String targetDir = ATTACHMENT_STORE_FILE_SYSTEM_LOCATION;
Maybe it is not needed to create a separate variable instead `ATTACHMENT_STORE_FILE_SYSTEM_LOCATION` could be used directly.
`String targetDir = ATTACHMENT_STORE_FILE_SYSTEM_LOCATION;`

2021-06-03 14:53 UTC, ravi110336 commented
@JaideepPalit ,Thanks for the review, Incorporated the changes as per the comments, Please check.

2021-06-07 07:27 UTC, JaideepPalit approved these changes
Code looks fine to me.
Tested attachment deletion from local file system successfully.

2021-06-07 07:28 UTC, merged