feat(rest): Added new endpoints to update attachment info of Project, Component, Release
eclipse/sw360 pull request #1190
Opened 2021-04-28 12:27 UTC by JaideepPalit

> Added new endpoints to update attachment info of Project, Component, Release.
> * Which issue is this pull request belonging to and how is it solving it? (*#1189*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: closes #1189 

### How To Test?
> Refer Rest Documentation
http://localhost:8080/resource/docs/api-guide.html#resources-project-attachment-info-update
http://localhost:8080/resource/docs/api-guide.html#resources-component-attachment-info-update
http://localhost:8080/resource/docs/api-guide.html#resources-release-attachment-info-update

> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2021-04-29 14:13 UTC, akapti requested changes
Reviewed the code, suggested some minor changes.
Tested the changes, and all the 3 endpoints working as expected.

2021-04-30 06:56 UTC, JaideepPalit commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ProjectSpecTest.java
> +
removed

2021-04-30 06:56 UTC, JaideepPalit commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
> +    public void updateAttachment(Attachment attachmentToUpdate, Attachment reqBodyAttachment, User user) {
changed to private

2021-04-30 06:56 UTC, JaideepPalit commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/attachment/Sw360AttachmentService.java
> +                Attachment actualAtt=matchingAttachment.get();
fixed

2021-04-30 06:58 UTC, JaideepPalit commented
Thanks for review and test.
Incorporated changes based on review comments

2021-05-03 10:44 UTC, akapti approved these changes
Code looks good.
Tested the PR again after changes, and is working fine.

2021-05-07 21:02 UTC, merged

2021-06-09 09:00 UTC, Lythenas commented
Is there a reason that the patch url is different from the get url?

To get the attachment infos you need to use `https://sw360.org/api/attachments/1234`
but to patch the same infos you need to use `https://sw360.org/api/attachment/1234`. I think this is really inconvenient.

It would also be nice if attachment infos could be updated through the `self` link (i.e. `https://sw360.org/api/attachments/5c597ceca6a04445b188daf8490e93b3`)

2021-06-09 09:40 UTC, mcjaeger commented
so, it is about the "s" ... I agree, but I am not sure how much trouble we cause will there be in case we change it