feat(SVM): Added new field transferToSVM(Default value - true) to determine whether linked project should be sent to SVM.
eclipse/sw360 pull request #1295
Opened 2021-07-05 20:39 UTC by JaideepPalit

> Added new field transferToSVM(Default value - true) to determine whether linked project should be sent to SVM.
>  * Request/Response structure of get_projects_with_all_details, get_project_by_id, create_project, update_project for linked project changed

> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: 

### How To Test?
> - Create Moderation Request for Project with Add, remove , update linked project with previous structure as in master.
> - Create Project with linked Project.
> - Run migration script `044_migrate_project_linked_project_relation.py` , `045_migrate_project_moderation_request_linked_project_relation.py`
> - Verify old Project Details, Edit, Delete.
> - Verify old Moderation request View, Accept.
> - Create New Project with/without linked project, test view, edit, delete.
> - Create new Moderation Request for Project with Add, remove , update linked project - verify view, approve.
> - Test Rest API - get_projects_with_all_details, get_project_by_id, create_project, update_project with/without linked project
> - Verify Usage table in detail/Edit page of Project which used by other project(i.e linked in other project)
 
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2021-07-07 12:07 UTC, JaideepPalit commented
Updated field names to `enableSvm` and `ProjectProjectRelationskip`

2021-07-21 04:53 UTC, smrutis1 commented
Reviewed it.
1. Please update the script numbering and readme.
2. Got this error while executing one of the script `045`. May be a `None` check is necessary.
![image](https://user-images.githubusercontent.com/46560890/126432783-ef2fa985-76bd-41c1-a087-5377232272ad.png)

2021-07-21 04:55 UTC, smrutis1 requested changes
Some observations

2021-07-21 04:55 UTC, smrutis1 commented on scripts/migrations/044_migrate_project_linked_project_relation.py
> +    print 'Total Projects with linkedProjects'
Please append the count, if it was intended to.

2021-07-21 07:46 UTC, JaideepPalit commented
Thanks for review.
1. Changed
2. Fixed

2021-07-21 13:30 UTC, smrutis1 commented
Have tested as per the mentioned steps. Working as expected.

Note: As there is structure change in API, the existing clients might break.

2021-07-21 13:35 UTC, smrutis1 approved these changes
Code looks good to me.

2021-07-22 14:47 UTC, JaideepPalit commented
(from discussion) - Added backward compatibility for `Create/update project with linked project`.
How to Test - 
   - Test Rest API -create_project, update_project with/without linked project
       - Old Structure for linked project
           ```
           "linkedProjects": {
                 "cf46ecaf1f2f9295xxxxxxxx" :  "UNKNOWN",
                 "cf46ecaf1f2f92xxxxxxxxxx": "UNKNOWN",
                 "cf46ecaf1f2f9xxxxxxxxxxx":   "UNKNOWN"
           }
          ```
     - New Structure  for linked Project
         ```
         "linkedProjects": {
                 "cf46ecaf1f2f9xxxxxxxxxxxx" :  {
                        "enableSvm": "false",
                        "projectRelationship": "CONTAINED"
                 },
                 "cf46ecaf1f2f92xxxxxxxxx": {
                        "enableSvm": "true",
                        "projectRelationship": "CONTAINED"
                 },
                 "cf46ecaf1f2f929xxxxxxxx":   {
                        "projectRelationship": "CONTAINED"
                 }
         }
         ```

2021-07-26 10:48 UTC, merged