fix(RequestUi):BU & ProjectName not loading for Closed CR table
eclipse/sw360 pull request #1299
Opened 2021-07-08 06:21 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

> Which issue is this pull request belonging to and how is it solving it?
- #1292 

> Did you add or update any new dependencies that are required for your change?
- No.

Issue: #1292 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?

> How should these changes be tested by the reviewer?

- `Project name`, and `business unit` should load for closed clearing request tables, If there are more CR in closed state.
- `Clearing Team` should be able to update the clearing request even if `Agreed Clearing Date` is passed.

> Have you implemented any additional tests?

- No.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Abdul Kapti <abdul.kapti@siemens-healthineers.com>

2021-07-13 07:51 UTC, JaideepPalit requested changes
Reviewed the PR.
Apart from minor review comment, code looks fine to me.

2021-07-13 09:26 UTC, JaideepPalit requested changes

2021-07-13 09:26 UTC, JaideepPalit commented on backend/src/src-projects/src/main/java/org/eclipse/sw360/projects/ProjectHandler.java
> +        assertNotEmpty(projects, "Invalid project Ids!");
Not sure, pls check whether assertion for empty project list is required and does not harm other endpoints calling the api,

![image](https://user-images.githubusercontent.com/56534710/125427369-74ea8a0f-ebb9-43ee-a714-b6cfdba7b062.png)

I guess , empty list is handled in `ProjectDatabaseHandler` - return empty list

2021-07-13 13:07 UTC, akapti commented
> Reviewed the PR.
> Apart from minor review comment, code looks fine to me.

Thanks for the review. Incorporated the requested changes.

2021-07-14 04:31 UTC, akapti commented
also added fix for `Open Clearing Request` table not loading.

2021-07-14 07:45 UTC, JaideepPalit approved these changes
Tested successfully on stage env.

2021-07-14 07:59 UTC, merged