feat(obligation): add function Edit/Duplicate/Changelog for Obligation
eclipse/sw360 pull request #1451
Opened 2022-01-25 07:27 UTC by quan-tv

Signed-off-by: Tran Vu Quan <quan1.tranvu@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> New functions for Obligation management
> * Edit one existing obligation
> * Create new obligation based on the information of one existing obligation (Duplicate)
> * View the changelogs of obligations

Issue: https://github.com/eclipse/sw360/issues/513

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> All new functions are available in the screen Admin -> Obligations
> Operations are similar to other existing Add/Edit/Changelog of SW360

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

2022-01-27 07:56 UTC, ravi110336 commented
Hi @quan-tv , could you please fix the merge conflicts.

2022-01-27 08:08 UTC, quan-tv commented
> Hi @quan-tv , could you please fix the merge conflicts.

Hi @ravi110336 ,

I've resolved the conflict.

2022-02-03 10:17 UTC, ravi110336 commented
Hi @quan-tv , I have reviewed and tested this PR and the new feature for the Obligation looks really good to me.
tested the different scenario for the obligation and validated the change log and everything working fine.

2022-02-10 10:54 UTC, quan-tv commented
I force pushed the new source code - minor update:
- Old source code: there is some case if user create an Obligation statement but don't fill the anything for Language element, Action and Object, the first Obligation statement in DB will be automatically selected.
- New source code: if user don't fill the Language element, Action and Object, there fields will be kept as empty.

2022-03-02 06:54 UTC, akapti requested changes
Tested the PR, and is working as expected.
Reviewed the code, and suggested some minor changes.

2022-03-03 09:14 UTC, quan-tv commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
> +    public static final String OBLIGATION_CHANGELOG = "obligationchangelog";
Updated the string value to 'obligation_changelog'

2022-03-03 09:22 UTC, quan-tv commented on backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
> +import org.eclipse.sw360.datahandler.thrift.changelogs.*;
Remove un-used imports

2022-03-03 09:22 UTC, quan-tv commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/DatabaseHandlerUtil.java
> +import org.eclipse.sw360.datahandler.thrift.licenses.*;
Updated follow comment

2022-03-03 09:22 UTC, quan-tv commented on backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
> +import org.eclipse.sw360.datahandler.common.*;
Updated follow comment

2022-03-03 09:23 UTC, quan-tv commented on backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
> +        if (lang.equals("") || action.equals("") || object.equals("")) {
Used utility function to check Null and Empty

2022-03-03 09:23 UTC, quan-tv commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/TodoPortlet.java
> +import org.eclipse.sw360.datahandler.thrift.changelogs.*;
Updated follow comment

2022-03-03 09:23 UTC, quan-tv commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/admin/TodoPortlet.java
> +        String obligatonId = request.getParameter(DOCUMENT_ID);
Corrected the variable name

2022-03-03 09:23 UTC, quan-tv commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/add.jsp
> +    // Keywords from OSADL obligation text
Deleted comment-out lines

2022-03-03 09:28 UTC, quan-tv commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/includes/obligationChangelog.jsp
> +        <div class="alert alert-danger"> Obligations Change Log is unavailable because Obligation is not existed. </div> </div> </div>')
Changed the message to 'Obligation Change Log is unavailable because Obligation does not exist.'

Putted the message to language properties file.

2022-03-04 05:25 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/includes/obligationChangelog.jsp
> +        <div class="alert alert-danger"> Obligations Change Log is unavailable because Obligation is not existed. </div> </div> </div>')
please add this text `obligation.change.log.is.unavailable.because.obligation.does.not.exist` in other 2 language files as well. (vi and jp)

2022-03-04 14:50 UTC, KoukiHama commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/includes/obligationChangelog.jsp
> +        <div class="alert alert-danger"> Obligations Change Log is unavailable because Obligation is not existed. </div> </div> </div>')
Note (Japanese ) : オブリゲーションが存在しないため、オブリゲーションのチェンジログは取得できません。

2022-03-07 03:45 UTC, quan-tv commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/admin/obligations/includes/obligationChangelog.jsp
> +        <div class="alert alert-danger"> Obligations Change Log is unavailable because Obligation is not existed. </div> </div> </div>')
Added message translation to 'Language_ja.properties' and 'Language_vi.properties'

2022-03-07 07:43 UTC, KoukiHama approved these changes

2022-03-08 06:55 UTC, akapti requested changes
Code looks good to me.
One issue I have noticed while testing.
If we try to duplicate the old obligation (previously existing), then I get following exception: `ERROR TodoPortlet:313 - Can not build json obligation textjava.lang.NullPointerException`

There are no issues when we create new obligation, or when we duplicate a newly created obligation.

to reproduce the issue, you can create a few obligations in `master` branch, then build this branch and try to duplicate the obligation created in `master` branch. it should throw null pointer exception.

2022-03-17 04:08 UTC, quan-tv commented
Dear @akapti ,

Thank you very much for spending time testing.

Unfortunately, I cannot re-procedure this issue.

Could you please provide the data of the obligation created in 'master' branch in 4 tables:
- Obligation
- ObligationElement
- ObligationList
- ObligationNode

Best regards,

2022-04-13 04:37 UTC, tienlee commented
I can re-procedure the duplicate issue. I am fixing it. Thank you.

2022-04-15 13:47 UTC, tienlee commented
> I can re-procedure the duplicate issue. I am fixing it. Thank you.

We fixed this issue. @akapti could you please check again?

2022-04-19 11:56 UTC, akapti approved these changes
Code looks good to me.
Tested the changes, and didn't found any issues. the functionalities (duplicate/edit/changelogs etc) are working fine.

2022-04-27 06:16 UTC, merged

2022-04-28 07:49 UTC, KoukiHama commented on .github/workflows/githubactions.yml
> +    branches: [ dev/feature-edit_and_clone_obligation ]
need to use [master]