feat(script): Addition to update project field starting with some value
eclipse/sw360 pull request #1456
Opened 2022-01-28 08:38 UTC by smrutis1

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

Addition to update project field starting with some value to a new value.

> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change? - No

Issue: 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?

Execute 003_update_project_field_value_couchdb_2_x.py
Following variables needs to be updated based on the requirement
1. fieldName = "field_to_be_migrated"
2. oldValue = "starting_with_string"
3. newValue = "replace_string"
4. isStartsWith = True

> Have you implemented any additional tests? - No

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-01-28 14:03 UTC, JaideepPalit requested changes
Code looks fine to me.

Kindly update Readme,md with new parameter

![image](https://user-images.githubusercontent.com/56534710/151560130-014d56f2-406f-4ce7-a4bb-b2b3767df800.png)

2022-01-31 06:06 UTC, smrutis1 commented
@JaideepPalit Thanks for review. Have updated the readme.

2022-02-02 08:21 UTC, ravi110336 commented
I have tested the script in stage and it is working fine.
Script has run for the below scenario, 
**1. change all: "SI DG SW..." to "SI GSW..."**
Please check the log file for the affected project ids- 003_update_project_field_value_couchdb_2_x.log

**2. change all: "SI DG EA-P&R" --> "SI EA R&D"**
Please check the log file for the affected project ids-  003_update_project_field_value_couchdb_2_x_UPDATE_SIDGEAPR.log
The above log file i have renamed it manually just to keep track on the updated project ids, later we can remove this.

2022-02-02 08:29 UTC, JaideepPalit approved these changes

2022-02-09 09:17 UTC, merged