feat(exportExcel): Generate and save excel to file system, Download generated file with token
eclipse/sw360 pull request #1477
Opened 2022-03-06 10:26 UTC by JaideepPalit

> Generate and save excel to file system, Download generated file with token.
> * Which issue is this pull request belonging to and how is it solving it? (*#1475*)
> * Did you add or update any new dependencies that are required for your change? - No

closes: #1475 

### How To Test?
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2022-03-22 08:27 UTC, smrutis1 commented
(from discussion): 
*  User will get an email once project spreadsheet export(i.e in `/tmp`) is completed with the download link.
*  set this `send.project.spreadsheet.export.to.mail.enabled = true` in sw360.properties file to enable this feature .

2022-03-30 08:01 UTC, ag4ums commented
report generation is breaking when multiple users tries to generate report

2022-04-20 08:05 UTC, smrutis1 commented
To reduce the size more you can remove many columns

| project name | version | group | project type | project tag | clearingState | name | release: version | component type | clearing state | ECC information: eccStatus | ECC information: ECCN | ECC information: assessorDepartment | ECC information: assessmentDate |

2022-04-20 10:40 UTC, Marco-Wagner commented
Yes only the mentioned colums are most important for a minimum set of an excel file.
The rest of the columns can be removed.
In my test it has reduced the size massivly.

2022-04-20 10:43 UTC, Marco-Wagner commented
PS: I want to mention here additionally that in my test saving the exported excel file from SW360 production instance over Microsoft Excel reduces the excel file to 10% of the file size (without column change)

2022-04-20 10:51 UTC, Marco-Wagner commented
Perhaps some excel compression option missing? :)

2022-04-22 12:38 UTC, akapti requested changes
reviewed the code. suggested some changes.

2022-04-22 12:38 UTC, akapti commented on libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java
> +            // logger
consider adding error log here.

2022-04-22 12:38 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +import java.io.InputStream;
remove unused import.

2022-04-22 12:38 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +            setSessionMessage(request, "Excel export has started. We will send you an email with download link once completed");
`Excel report generation has started` seems better. If possible add localization text.

2022-04-25 06:39 UTC, smrutis1 commented
@akapti Thanks for review. Have incorporated the changes.

2022-04-25 07:35 UTC, akapti approved these changes
Code looks good to me.
Approved.
Tested by: @ag4ums

2022-04-27 08:40 UTC, smrutis1 commented
Resolved merge conflicts

2022-04-28 13:07 UTC, merged