feat(UI): ModifiedOn & MOdifiedBy fields for Project/COmponent/Release
eclipse/sw360 pull request #1539
Opened 2022-05-24 14:39 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
Added `ModifiedBy` and `ModifiedOn` fields for `Project`, `Component` and `Release.

Issue: #1479 

### How To Test?

- Modify / Update the project , component and release from UI and REST API. You should be able to see the `ModifiedOn` and `ModifiedBy` fields values in UI.
- Merge / Split the `Component`, Only the component that got merged should have appropriate `ModifiedOn` and `ModifiedBy` fields values.
- These 2 fields are not exposed via `REST` API. (in order to avoid changes in response structure) 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Abdul Kapti <abdul.kapti@siemens-healthineers.com>

2022-06-07 07:43 UTC, kumarnikesh commented
Test is successful.

2022-06-09 06:48 UTC, smrutis1 requested changes
One minor changes requested w.r.t properties file

2022-06-09 06:48 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> +modified.date.yyyy.mm.dd=Modified date YYYY-MM-DD
Please update it in other Language properties file as well.

2022-06-09 06:56 UTC, KoukiHama commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> +modified.date.yyyy.mm.dd=Modified date YYYY-MM-DD
FYI ;  Japanese
modified.date.yyyy.mm.dd=修正日 YYYY-MM-DD

2022-06-13 05:47 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> +modified.date.yyyy.mm.dd=Modified date YYYY-MM-DD
> Please update it in other Language properties file as well.

Done. Thanks.

2022-06-17 12:40 UTC, smrutis1 approved these changes
Code looks good.

2022-06-18 05:59 UTC, merged