Feat (Vulnerability): Improve add/update/delete vulnerability APIs implement add/update/delete vulnerability by GUI
eclipse/sw360 pull request #1550
Opened 2022-06-07 08:47 UTC by hoangnt2

Feat (Vulnerability): Improve add/update/delete vulnerability APIs implement add/update/delete vulnerability by GUI

Issue: 
#1170 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?

### 1. Implement create, update, delete vulnerability by GUI
Refer to #1170

### 2. Improvement vulnerability REST API
* Create a vulnerability

```
curl 'https://sw360.org/api/vulnerabilities' -i -X POST -H 'Content-Type: application/hal+json'
 -H 'Authorization: Bearer eyJhbGciOi*******' -H 'Accept: application/hal+json' 
 -d '{
 "externalId" : "987",
 "title" : "Title of vulnerability 12345",
 "description" : "Description of vulnerability",
 "publishDate" : "01-01-2018",
 "lastExternalUpdate" : "last-update-id-123",
 "priority" : "high",
 "priorityText" : "Priority Text",
 "action" : "new",
 "impact" : {
   "Key 1" : "Value 1",
   "Key 2" : "Value 2"
 },
 "legalNotice" : "Legal Notice",
 "assignedExtComponentIds" : [ "comp-id-2", "comp-id-1" ],
 "cveReferences" : [ 
     "2021-1111",
     "2022-2222"
  ],
 "vendorAdvisories" : [ {
   "vendor" : "vendor1",
   "name" : "name1",
   "url" : "http://url1"
 }, {
   "vendor" : "vendor2",
   "name" : "name2",
   "url" : "http://url2"
 } ],
 "extendedDescription" : "Extended Description",
 "references" : [ "reference-1", "reference-2" ],
 "cvss" : "3.0",
 "cvssTime" : "2019-01-01",
 "vulnerableConfiguration" : {
   "Key 1" : "Value 1",
   "Key 2" : "Value 2"
 },
 "access" : {
   "Key 1" : "Value 1",
   "Key 2" : "Value 2"
 },
 "cwe" : "common weakness enumeration",
 "cveFurtherMetaDataPerSource" : {
   "Cve meta data" : {
     "Key 1" : "Value 1",
     "Key 2" : "Value 2"
   }
 }
}'

```

* Update vulnerability 
```
curl 'https://sw360.org/api/vulnerabilities/98765' -i -X PATCH -H 'Content-Type: application/hal+json' -H 'Authorization: Bearer eyJhbGciOiJSUzI1N*********' -H 'Accept: application/hal+json' -d '{
  "externalId" : "98765",
  "title" : "Updated Title",
  "description" : "Description of vulnerability",
  "publishDate" : "01-01-2018",
  "lastExternalUpdate" : "last-update-id-123",
  "priority" : "high",
  "priorityText" : "Priority Text",
  "action" : "new",
  "impact" : {
    "Key 1" : "Value 1",
    "Key 2" : "Value 2"
  },
  "legalNotice" : "Legal Notice",
  "assignedExtComponentIds" : [ "comp-id-2", "comp-id-1" ],
  "cveReferences" : [ 
     "2021-1111",
     "2022-2222"
  ],
  "vendorAdvisories" : [ {
    "vendor" : "vendor1",
    "name" : "name1",
    "url" : "http://url1"
  }, {
    "vendor" : "vendor2",
    "name" : "name2",
    "url" : "http://url2"
  } ],
  "extendedDescription" : "Extended Description",
  "references" : [ "reference-1", "reference-2" ],
  "cvss" : "3.0",
  "cvssTime" : "2019-01-01",
  "vulnerableConfiguration" : {
    "Key 1" : "Value 1",
    "Key 2" : "Value 2"
  },
  "access" : {
    "Key 1" : "Value 1",
    "Key 2" : "Value 2"
  },
  "cwe" : "common weakness enumeration",
  "cveFurtherMetaDataPerSource" : {
    "Cve meta data" : {
      "Key 1" : "Value 1",
      "Key 2" : "Value 2"
    }
  }
}'
```
* Other method refer to: http://localhost:8080/resource/docs/api-guide.html#resources-vulnerabilities

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-10-18 09:01 UTC, nikkuma7 commented
Test successful.

2022-11-16 06:23 UTC, smrutis1 requested changes
some changes requested

2022-11-16 06:23 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/vulnerabilities/VulnerabilitiesPortlet.java
> +            log.info("Error remove param url: {}", e.getMessage());
Please make it `log.error`

2022-11-16 06:23 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/vulnerabilities/VulnerabilitiesPortlet.java
> +    public static void updateVulnerabilityFromRequest(PortletRequest request, Vulnerability vulnerability) throws ParseException {
Please move this to backend

2022-11-16 06:23 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/vulnerabilities/VulnerabilitiesPortlet.java
> +    public static RequestStatus deleteVulnerability(PortletRequest request, Logger log) {
Please move this to backend

2022-11-16 06:23 UTC, smrutis1 commented on rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
> +                //"publishDate",
please remove the commented lines

2022-11-16 07:34 UTC, KoukiHama commented
We will update soon, Thank you for reviewing.

2022-11-25 12:00 UTC, smrutis1 approved these changes
Code looks ok

2022-12-02 02:20 UTC, hoangnt2 commented
@smrutis1  Can you remove **needs code review** label?

2022-12-14 05:11 UTC, merged