fix(CrUi): fix the critical CR creation issue
eclipse/sw360 pull request #1569
Opened 2022-06-23 05:41 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

SW360 user were not able to create the `critical` clearing request, 
The issue was due:
- The critical CR from other group / department were also considered while fetching the count.
- There were `closed` CR in `critical` state.

Changes: 
- This PR includes changes in logic of fetching the `critical` CR count from database.
- This PR will make the critical CR mutually exclusive from user group (department).
- Now only critical CR in `open` state and the CR that belong to user `group` will be counted.

Issue: #1564 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?

- Login as a user from department `X`, Create 2 `critical` CR for project belonged to department `X`.
- Now login as a user from department `Y`, and you should be able to create up to 2 `critical` CR for project belonged to department `Y`.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Abdul Kapti <abdul.kapti@siemens-healthineers.com>

2022-06-29 10:49 UTC, rudra-superrr commented
This functionality is working properly when project is linked with release(s).
But there is an issue when no release is linked with the project i.e. Open Clearing Requests table not loading properly and showing "Loading..." in some field values. 

![ClearingReport](https://user-images.githubusercontent.com/58290634/176419119-2e7f1758-a567-4275-b614-f2f8abb2860c.PNG)

2022-07-01 17:38 UTC, akapti commented
> This functionality is working properly when project is linked with release(s). But there is an issue when no release is linked with the project i.e. Open Clearing Requests table not loading properly and showing "Loading..." in some field values.

The issue has been fixed.

2022-08-16 09:44 UTC, rudra-superrr commented
Testing was successful.

2022-08-29 11:13 UTC, smrutis1 requested changes
minor change requested

2022-08-29 11:13 UTC, smrutis1 commented on backend/src/src-moderation/src/main/java/org/eclipse/sw360/moderation/db/ClearingRequestRepository.java
> +        return CommonUtils.nullToEmptySet(criticalCr).stream()
May be use `.distinct().count()` here after filter instead of collecting in Set and getting size.

2022-09-07 06:05 UTC, smrutis1 approved these changes
Code looks good.

2022-09-15 07:44 UTC, merged