feat(ReleaseUi):Display AssessmentSummary info from CLi in Release details page
eclipse/sw360 pull request #1578
Opened 2022-06-30 07:02 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
* Conditions to be met in order to display the `Assessment Summary Information` in `Clearing Details` tab of `Release Details` page:
* There should be only `ONE CLI` in Release Attachments, and in case of multiple CLI files attached in release then there should be `ONLY ONE ACCEPTED CLI` in Release Attachment.
* If the above condition is not met, then `Show Assessment Summary Info` button will not be shown.
* `Assessment Summary` information should be present in CLI, else appropriate message will be shown.

Issue: #1577 

### How To Test?

- Create a Release, and upload a `CLI` attachment in Release.
- Now You'll see the button `Show Assessment Summary Info`.
- Clicking on this button should load the Assessment summary information in the UI.

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

Signed-off-by: Abdul Kapti <abdul.kapti@siemens-healthineers.com>

2022-07-01 06:38 UTC, rudra-superrr commented
Testing was successful.

2022-07-06 06:01 UTC, smrutis1 requested changes
Some minor review comments

2022-07-06 13:54 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/css/components/_table.scss
> +    td.comment-text {
fixed Indentation

2022-07-06 13:54 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/css/main.scss
> +        thead.cursor {
fixed Indentation

2022-07-06 13:54 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
> +            if (CommonUtils.isNullOrEmptyMap(assessmentSummaryMap) || assessmentSummaryMap.size() < 1) {
Thanks, removed the second condition.

2022-07-06 13:55 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
> +            assessmentSummaryMap = licenseInfoResult.get(0).getLicenseInfo().getAssessmentSummary();
added null and empty check for `licenseInfoResult`

2022-07-11 05:52 UTC, merged

2022-10-26 11:51 UTC, KoukiHama commented
@akapti  @smrutis1 

I want to try this function, but I dont know how to make valid CLI xml for this function.
Can I make its xml by fossology?