fix/svmcomponentids - do not copy svm component ids
eclipse/sw360 pull request #1580
Opened 2022-07-01 08:01 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*) 
> * Did you add or update any new dependencies that are required for your change? No

Issue: 
Do not copy any SVM component ids
https://code.siemens.com/sw360/sw360portal/-/issues/1071

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
1)Goto component tab
2)click on component name
3)select release overview
4)We will find the list of name, then click on version 
5)click on edit Release button
6)Add external ids and values, then update Release button
7) then go back and click on dublicate.
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-07-06 06:28 UTC, smrutis1 commented
1. Create the issue in github issue space and refer the same in description.
2. Please refer the semantic commit message types and update accordingly.

```feat (new feature for the user, not a new feature for build script)
fix (bug fix for the user, not a fix to a build script)
docs (changes to the documentation)
style (formatting, missing semi colons, etc; no production code change)
refactor (refactoring production code, eg. renaming a variable)
test (adding missing tests, refactoring tests; no production code change)
chore (updating grunt tasks etc; no production code change)

2022-07-06 11:11 UTC, smrutis1 commented
(from discussion): 
SW360 must not copy the external Id with specific key, while cloning a release.

2022-07-21 08:15 UTC, smrutis1 requested changes
Please make the property value blank and set the logic accordingly

2022-07-21 08:15 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/sw360.properties
> +externalId.remove.while.cloning.release=com.siemens.svm.component.id
Please remove this siemens specific key in the properties file.

2022-07-28 10:34 UTC, rudra-superrr commented
Testing was successful.

2022-08-24 04:36 UTC, smrutis1 commented
@nikkuma7 Please squash the commits

2022-08-24 05:34 UTC, smrutis1 requested changes

2022-08-24 05:34 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
> +        EXTERNALID_BLOCKLIST_CLONING_RELEASE = props.getProperty("externalId.remove.while.cloning.release", "");
May be rename it to `release.externalId.to.be.removed.while.cloning` for better readability.

2022-08-24 05:34 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortletUtils.java
> +                extIdHmap.remove(names.getKey());
There is a possibility of `ConcurrentModificationException` here, so to avoid please consider to use `ConcurrentHashMap`

2022-09-06 07:13 UTC, smrutis1 commented
Please amend the commit message.

![image](https://user-images.githubusercontent.com/46560890/188570008-09c462a4-b3ee-4483-8495-51d723cf8af8.png)

2022-09-06 11:32 UTC, nikkuma7 commented
Issue is resolve successfully.

2022-09-06 11:34 UTC, nikkuma7 commented
![image](https://user-images.githubusercontent.com/49710817/188625692-1b682259-3988-498d-806f-9e101edd9769.png)

2022-09-22 09:35 UTC, smrutis1 approved these changes
Code looks ok

2022-09-28 06:44 UTC, smrutis1 approved these changes
Code looks good

2022-09-30 08:49 UTC, merged