feat(SPDX): Use new SPDX library (#1496)
eclipse/sw360 pull request #1594
Opened 2022-07-18 02:15 UTC by tuannn2

Signed-off-by: tuan99123 <tuan2.nguyennhu@toshiba.co.jp>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #1496

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?

> Import Project and Component

> I think example.rdf file (https://github.com/eclipse/sw360/pull/653), itself has some issue. I will provide you with file in  https://github.com/spdx/tools/tree/master/Examples for you to use for testing.

> This is the validation tool for SPDX file: https://tools.spdx.org/app/validate/

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-07-19 23:12 UTC, KoukiHama commented
This PR does not change any SW360 functionality, it just changes the SPDX library used by SW360.
Testing should confirm that all existing SPDX related functionality is working fine.

2022-08-31 08:44 UTC, tienlee commented
I would like to attach the slides which are used in our telco today.
Let's keep to discuss the json format between anchore/syft and a perfect SPDX file (SPDXJSONExample-v2.2.spdx.json)

[SW360-20220831 - Demo1594.pptx](https://github.com/eclipse/sw360/files/9460025/SW360-20220831.-.Demo1594.pptx)

2022-09-12 09:16 UTC, akapti commented
Hi @tuannn2 
I feel that rebase didn't went well, because PR contains changes which is totally unrelated to SPDX library upgrade.

for example:

It includes changes related to ChangeLogs in following file: https://github.com/eclipse/sw360/pull/1594/files#diff-29f4181fef7f3e6f651dde38f70234ffa90ccc0f7cfebb9cdd258071f8aa2e01 , https://github.com/eclipse/sw360/pull/1594/files#diff-e06edfe0b28e68467281adcf719a12122b6ca9565682e3523ea33ed4d39a52c7, https://github.com/eclipse/sw360/pull/1594/files#diff-7b84421f5372707112717574bd301252e3c831d747c1164593d83a2dbde26acf and few more files.


also the PR contains changes related to Thrift configuration in following files: https://github.com/eclipse/sw360/pull/1594/files#diff-c70fecc2e6dc5d8dc0441ca5fa4c26f109ebd954b2192cf3b4b5def24e24f23f

also removed changes related to Reading Obligation from README OSS in following files: https://github.com/eclipse/sw360/pull/1594/files#diff-74ca1a57d71f7fae13d891c82005a0a933bc9d39ab88b105ac531dc50f31712eL2706 and https://github.com/eclipse/sw360/pull/1594/files#diff-a47079862cba8e2c7eb02695e28dcd5e1016bdca7338e88075985b5dcb0e80baL308

Let me know in case I am wrong or if I missed something.
Or Can you please explain why changes related to ChangeLogs, Thrift configuration and ReadMe OSS obligations are part of this PR?

2022-09-12 09:30 UTC, tuannn2 commented
Thank you for your reviewing, @akapti.
I will check and reply to you as soon as possible!

2022-09-12 11:31 UTC, akapti requested changes
I have only reviewed the code.
will do the testing later.
Kindly incorporate the requested changes.

2022-09-12 11:31 UTC, akapti commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +import java.nio.file.Paths;
Please remove all the unused imports.

2022-09-14 06:48 UTC, tienlee commented on backend/src-common/pom.xml
> +            <version>1.0.2</version>
Thank you for your review.
We tried to upgrade the library but can't import SPDX files with 1.0.4. We are debugging to find the root cause.
Other comments were fixed.

2022-09-15 03:58 UTC, akapti commented on backend/src-common/pom.xml
> +            <version>1.0.2</version>
Thanks much @tienlee  .
I will also give it a try in my local environment with version `1.0.4`.

2022-09-15 05:56 UTC, heliocastro commented on backend/src-common/pom.xml
> +            <version>1.0.2</version>
Please add the versions on root pom.xml, and the dependencies on DependencyManagement.

2022-09-15 06:05 UTC, akapti commented on backend/src-common/pom.xml
> +            <version>1.0.2</version>
slack reference: https://sw360chat.slack.com/archives/C02NGJ2LX08/p1663221609110229

2022-09-20 11:44 UTC, tienlee commented
@akapti and @heliocastro , we have committed to new changes. Please help me to check these changes.

2022-09-21 08:09 UTC, mcjaeger commented
(from meeting:) needs re-review and re-test after PR comments have been implemented

2022-09-28 15:52 UTC, akapti requested changes
Suggested some minor review comments. Please incorporate.

Tested the feature and it's working fine without any issues.

2022-09-29 01:44 UTC, tienlee commented
> Suggested some minor review comments. Please incorporate.
> 
> Tested the feature and it's working fine without any issues.

Thank you very much. We will fix these minor defects soon.

2022-09-29 06:40 UTC, akapti approved these changes
Code looks good to me.
Tested the changes and it's working as expected.

2022-09-30 11:52 UTC, akapti commented
@tuannn2 @KoukiHama 
The existing ( and old SBOM import) functionality is such that whenever we import components from SBOM it does not set the `component type` field in component.
Since Component type is mandatory field in `UI` and `REST` API while creating the component.
It would be really good if we can set the `component type` to `OSS` while importing the components from SBOM. 

Kindly include this change in the current PR if possible, or else create a new PR.

2022-09-30 11:55 UTC, KoukiHama commented
@akapti 

ok. I agree the idea about  components field

Could you merge this PR and make new issue and assign it to me?

2022-09-30 11:58 UTC, KoukiHama commented
@akapti 

ok. I agree the idea about  components field

Could you merge this PR and make new issue and assign it to me?

we want to do it as new issue.

2022-09-30 12:07 UTC, KoukiHama commented
@tienlee do you have idea about component type issue.

2022-10-03 02:01 UTC, tienlee commented
> @tienlee do you have idea about component type issue.

I think this is a bug from the old version. Please create new issue and I will fix it.

2022-10-03 03:09 UTC, akapti commented
> I think this is a bug from the old version. Please create new issue and I will fix it.

Created an issue #1658 . It's an already existing issue.
You can work on the above issue once this PR is merged.

2022-10-03 08:28 UTC, merged