fix(UI): Disable write access from UI
eclipse/sw360 pull request #1598
Opened 2022-07-22 08:14 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? #1597
> * Did you add or update any new dependencies that are required for your change? No

Issue: 
No use of write access on preferences page, so we removed write access from UI
### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer? 
1) First reviewer login into sw360 project 
2) Go to preferences tab
3) Go down on the same page and write access will not be there.
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-07-27 00:58 UTC, akapti requested changes
Tested the changes.
The feature is working fine, but the confusion is:

- write token checkbox is disabled when the property `preferenses.write.access.disable` value is set to `false`.
- and checkbox is enabled when we set the property value to `true`.

Ideally it should work other way round based on name of property key (`preferenses.write.access.disable`).

2022-08-16 12:42 UTC, akapti requested changes
Kindly incorporate one minor review comment.

2022-08-16 12:42 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/preferences/UserPreferencesPortlet.java
> -
Please don't remove this line.. also at line 188.. Keep this class unchanged.

2022-08-16 12:43 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/preferences/view.jsp
> +                                            <label class="form-check-label" for="authorities_write"><liferay-ui:message key="write.access" /></label>
still there is whitespace at end of line number `162`.

2022-08-18 07:12 UTC, nikkuma7 commented
I have modified the code.

2022-08-19 17:34 UTC, akapti requested changes
One minor review comment.
Please squash multiple commits.

2022-08-19 17:34 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/common/PortalConstants.java
> +    public static final Boolean DISABLE_REST_API_WRITE_ACCESS_TOKEN_IN_PREFERENCES;
please rename this field to `REST_API_WRITE_ACCESS_TOKEN_IN_PREFERENCES`... in line with property key.

2022-08-24 07:02 UTC, akapti approved these changes
Looks good to me.

2022-09-05 08:21 UTC, akapti requested changes
Getting following while testing the PR.

```
2022-09-05 08:20:04.747 ERROR [http-nio-8080-exec-3][PortletRequestDispatcherImpl:304] Unable to dispatch request: PWC6033: Error in Javac compilation for JSP__PWC6197: An error occurred at line: 33 in the jsp file: /html/preferences/view.jsp_PWC6199: Generated servlet error:_cannot find symbol_  symbol:   variable DISABLE_REST_API_WRITE_ACCESS_TOKEN_IN_PREFERENCES_  location: class org.eclipse.sw360.portal.common.PortalConstants__PWC6199: Generated servlet error:_view_jsp.java uses or overrides a deprecated API.__PWC6199: Generated servlet error:_Recompile with -Xlint:deprecation for details.__PWC6199: Generated servlet error:_view_jsp.java uses unchecked or unsafe operations.__PWC6199: Generated servlet error:_Recompile with -Xlint:unchecked for details.__ [Sanitized]
2022-09-05 08:20:04.749 ERROR [http-nio-8080-exec-3][PortletServlet:119] null
com.liferay.portal.kernel.log.LogSanitizerException: javax.portlet.PortletException: org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP__PWC6197: An error occurred at line: 33 in the jsp file: /html/preferences/view.jsp_PWC6199: Generated servlet error:_cannot find symbol_  symbol:   variable DISABLE_REST_API_WRITE_ACCESS_TOKEN_IN_PREFERENCES_  location: class org.eclipse.sw360.portal.common.PortalConstants__PWC6199: Generated servlet error:_view_jsp.java uses or overrides a deprecated API.__PWC6199: Generated servlet error:_Recompile with -Xlint:deprecation for details.__PWC6199: Generated servlet error:_view_jsp.java uses unchecked or unsafe operations.__PWC6199: Generated servlet error:_Recompile with -Xlint:unchecked for details.__ [Sanitized]
```

Please fix it.
screenshot: 
![image](https://user-images.githubusercontent.com/50870174/188402945-f1e07652-2d9b-4cf6-954a-779bba4138aa.png)

2022-09-13 07:24 UTC, akapti approved these changes
code looks good. working as expected.

2022-09-15 07:46 UTC, merged