fix(rest): Added component type tag in release api
eclipse/sw360 pull request #1608
Opened 2022-08-10 04:36 UTC by nikkuma7

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? #1607 
> * Did you add or update any new dependencies that are required for your change? yes, I added component type tag under release API.

Issue: 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
> How should these changes be tested by the reviewer?
1) Go to component tab and click on any component name.
2) If you need to change in the exiting component or you can select Release Overview tab.
3)click on version and copy release Id and test it in postman.
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-08-10 10:42 UTC, rudra-superrr commented
Testing was successful but only for Getting a single release by REST.
Component type field not showing for other rest call related to releases.

2022-09-09 11:01 UTC, rudra-superrr commented
Testing was successful.

2022-09-15 07:07 UTC, smrutis1 requested changes

2022-09-15 07:07 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> +                                fieldWithPath("componentType").description("The componentType of the release"),
Add all possible values

2022-09-15 07:07 UTC, smrutis1 commented on rest/resource-server/src/test/java/org/eclipse/sw360/rest/resourceserver/restdocs/ReleaseSpecTest.java
> +                        fieldWithPath("componentType").description("The componentType of the release"),
Add all possible values

2022-09-20 13:28 UTC, smrutis1 approved these changes
Code looks good.

2022-09-30 08:50 UTC, merged