fix(ProjectUI): Error when creating/editing duplicate project
eclipse/sw360 pull request #1687
Opened 2022-10-19 10:38 UTC by afsahsyeda

Signed-off-by: afsahsyeda <afsah.syeda@siemens-healhtineers.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
The edit page is retained after 'DUPLICATE' error message is thrown.

Issue: 
Error on creating/editing duplicate project(existing name and version).
### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
1)Add a project with the same name and version as an existing project.
2) Click on Create project button.

1) Edit a project with same name and version of a different existing project.
2) Click on Update Project button.

An error stating 'Project with same name and version already exists' will pop up but the edit page will be retained to allow the required changes.
### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-10-31 06:59 UTC, rudra-superrr commented
Testing was successful.

2022-11-09 01:16 UTC, akapti requested changes
One issue I noticed while testing is that linked sub-projects and attachments are not retained. 
![image](https://user-images.githubusercontent.com/50870174/200712283-0db0b3f7-99f9-4f99-bfd2-b786279b6107.png)


All the data entered by user is retained except linked sub-projects (creating a duplicate project or editing an existing project) and attachments (only when editing existing project).

2022-11-09 01:29 UTC, akapti commented
One more thing... The exact same issue is present for Component as well.
![image](https://user-images.githubusercontent.com/50870174/200713046-b48f2234-0d87-430e-956a-a94a12d183a5.png)


It would be really great if the component issue can also be fixed or create a new issue for that and provide a fix in another PR.

2022-11-16 06:30 UTC, afsahsyeda commented
Hi @akapti ,

Please check for similar changes implemented in the Component portlet.

2023-02-22 05:31 UTC, smrutis1 requested changes
Requesting for some minor validations

2023-02-22 05:31 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +                project = project == null ? client.getProjectByIdForEdit(id, user) : project;
Is there any significant of this line?

2023-02-22 08:48 UTC, afsahsyeda commented
Hi @smrutis1 ,
 I have reused the OBJECT_MAPPER instance and removed ternary expression in ProjectPortlet as I did not see any change after removing the line.

2023-02-28 03:08 UTC, smrutis1 approved these changes
Code looks ok

2023-02-28 11:39 UTC, merged