fix(UI): Added code to show the project list in component tab
eclipse/sw360 pull request #1698
Opened 2022-10-26 05:56 UTC by nikkuma7

Signed-off-by: Nikesh kumar <kumar.nikesh@simens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? #1697 
> * Did you add or update any new dependencies that are required for your change? No

Issue: 
There is an issue with project list which is not showing in component tab.
### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
1: Login sw360 
2: Go to component tab.
3: select any component and go inside the component.
4:scroll down and see the project list.

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-11-09 00:58 UTC, akapti requested changes
tested the PR, working fine.
screenshot of component details page:
![image](https://user-images.githubusercontent.com/50870174/200709917-b2506ad7-4a09-4822-9370-0e82f8d41379.png)



The exact same issue is present for Projects details page as well, where in sub projects are not listing it's parents projects(used by). attached sample screenshot below. Please fix it as well.

![image](https://user-images.githubusercontent.com/50870174/200709876-64f66ef6-fb95-4ad8-a2ae-27f1d6867e60.png)

2022-11-09 00:58 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
> +                             <core_rt:set var="tableId" value="usingProjectsTableSummary"/>
align it properly.

2022-11-09 07:26 UTC, nikkuma7 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/includes/components/detailOverview.jspf
> +                             <core_rt:set var="tableId" value="usingProjectsTableSummary"/>
done.

2022-11-10 11:03 UTC, akapti approved these changes
Code looks good.
tested the changes and used by projects are listing in both project and component details page.

Testing screenshot:
![image](https://user-images.githubusercontent.com/50870174/201074766-eecabd19-f495-4458-a88f-a79db597bf40.png)

2022-11-10 11:14 UTC, merged