fix(SPDX):  Import SPDX licenses File with new SPDX library (tools-java 1.0.4)
eclipse/sw360 pull request #1700
Opened 2022-11-01 09:44 UTC by tuannn2

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: #1699

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
1. Go to License Page in Tab Admin
2. Import File: (Please remove .txt before import)
[SPDX2_zlib128.zip_example-spdx 2.rdf.txt](https://github.com/eclipse/sw360/files/9908684/SPDX2_zlib128.zip_example-spdx.2.rdf.txt) 
3. Check License in tab License in Home Page

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-11-01 09:52 UTC, KoukiHama commented
Is this PR  fix "obligation import" and "license import" ?

2022-11-01 10:08 UTC, KoukiHama commented
I am not sure why the test Import File?
#1699 mention about  "Import SPDX licenses" button in admin/license page, not importing 
spdx ref file.
@tuannn2

2022-11-01 10:21 UTC, tienlee commented
> I am not sure why the test Import File? #1699 mention about "Import SPDX licenses" button in admin/license page, not importing spdx rdf file. @tuannn2

Issue 1699 was found by @shi9qiu . I will discuss with @tuannn2 and @shi9qiu , then feedback you tomorrow.

2022-11-02 01:39 UTC, tuannn2 commented
Thank you @KoukiHama,
I'm a bit confused. Really don't need to import the File, just test and click Import SPDX Information.

2022-11-30 10:42 UTC, akapti requested changes
Tested the changes in local, and working fine.
suggested a review comment, please incorporate.

screenshot for reference:
![image](https://user-images.githubusercontent.com/50870174/204775238-f14741a8-e8df-4e03-b969-c7e45946059c.png)

2022-11-30 10:42 UTC, akapti commented on backend/src/src-licenses/pom.xml
> +            <version>1.1.1</version>
Kindly define the version in parent (main) `pom.xml` file, and include it here.
also consider removing the maven repo link in comment on line `36`.

2022-11-30 10:42 UTC, akapti commented on backend/src/src-licenseinfo/pom.xml
> +            <version>1.1.1</version>
Kindly define the version in parent (main) `pom.xml` file, and include it here.
also consider removing the maven repo link in comment on line `34`.

2022-12-01 08:25 UTC, akapti approved these changes
Looks good to me.
tested and successfully imported SPDX licenses.
![image](https://user-images.githubusercontent.com/50870174/205003003-08dad561-6aec-4fbb-82d3-5c54a226a946.png)

2022-12-01 09:52 UTC, merged