fix(ProjectUI): Multiple alerts when there are similar linked projects
eclipse/sw360 pull request #1714
Opened 2022-11-11 07:46 UTC by afsahsyeda

Signed-off-by: afsahsyeda <afsah.syeda@siemens-healhtineers.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Description:
If the subprojects of a project have similar linked projects, they are being initialized multiple times, causing several alert messages to appear. Hence the projects will now appear only once in the tablist of Vulnerabilities.

Issue: #1704 

### How To Test?
> Link projects to a parent project.
> Link similar projects to two or more of the child projects.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/115608771/201289348-5f4297ed-988b-4b23-a910-4a7821e549f2.png)

2022-11-16 06:48 UTC, nikkuma7 commented
Test successful.

2022-11-17 10:22 UTC, akapti requested changes
Kindly incorporate the requested changes.

2022-11-17 10:22 UTC, akapti commented on frontend/configuration/portal-ext.properties
> +sql.data.com.liferay.portal.kernel.model.Country.country.id=21539
we don't need this changes. kindly revert it.

2022-11-17 10:22 UTC, akapti commented on libraries/datahandler/src/main/resources/couchdb.properties
> +#
please delete this file.

2022-11-17 10:22 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +                Set<ProjectLink> subprojects = allSubProjectLinks.parallelStream().map(l -> l.getSubprojects()).flatMap(l-> l.stream())
convert `List<ProjectLink> allSubProjectLinks` to `Map<String, ProjectLink>` and pass the `values()` of Map in request attribute. <br>

Kindly revert unwanted changes in Line # `102` and `1635` 
fix indentation on line # `2127`

2022-11-23 06:13 UTC, closed without merging