Fix(Obligation): Fix bug can not add/update Admin Obligation and import OSADL
eclipse/sw360 pull request #1738
Opened 2022-11-28 02:16 UTC by hoangnt2

Fix bug can not add/update Admin Obligation and import OSADL

Issue: #1734 

### How To Test?
Refer to: #1734 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2022-11-30 11:09 UTC, akapti requested changes
Suggested couple of review comments.

Tested the changes and it's working as expected.
here is the screenshot for reference:
![image](https://user-images.githubusercontent.com/50870174/204779052-b28aace1-87d3-43ca-bd17-6acec0afe8b2.png)



I suggest you to remove the usage of deprecated class `org.json.simple.JSONObject`  in function `importAllOSADLLicenses` and use the new class `org.json.JSONObject`.
You can use `length()` method instead of `org.json.simple.JSONObject` -> `size()` method wherever there are compile time error. (at line [969](https://github.com/eclipse/sw360/blob/main/backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java#L969))

2022-12-01 05:01 UTC, hoangnt2 commented
@akapti I corrected them according to your comment, please check

2022-12-01 08:28 UTC, akapti approved these changes
looks good to me.
tested the changes, and successfully imported OSADL obligations into SW360.

2022-12-01 08:43 UTC, akapti commented
For some reason import failed with the following error.
I tried to import when there are already existing OSADL obligations in Sw360.

```
2022-12-01 08:39:42 ERROR LicenseDatabaseHandler:1122 - Can not build obligation text from node json object: {"val":["Obligation","YOU MUST NOT","Promote",""],"children":[]}
2022-12-01 08:39:42 ERROR ProcessFunction:47 - Internal error processing importAllOSADLLicenses
java.lang.NullPointerException: null
	at org.eclipse.sw360.licenses.db.LicenseDatabaseHandler.importAllOSADLLicenses(LicenseDatabaseHandler.java:946) ~[src-licenses-16.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.licenses.LicenseHandler.importAllOSADLLicenses(LicenseHandler.java:322) ~[src-licenses-16.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.licenses.LicenseService$Processor$importAllOSADLLicenses.getResult(LicenseService.java:3833) ~[datahandler-16.0.0-SNAPSHOT.jar:?]
	at org.eclipse.sw360.datahandler.thrift.licenses.LicenseService$Processor$importAllOSADLLicenses.getResult(LicenseService.java:3813) ~[datahandler-16.0.0-SNAPSHOT.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) [libthrift-0.16.0.jar:0.16.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) [libthrift-0.16.0.jar:0.16.0]
	at org.apache.thrift.server.TServlet.doPost(TServlet.java:83) [libthrift-0.16.0.jar:0.16.0]
	at org.eclipse.sw360.projects.Sw360ThriftServlet.doPost(Sw360ThriftServlet.java:40) [src-common-16.0.0-SNAPSHOT.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [servlet-api.jar:4.0.FR]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.56]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) [catalina.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [catalina.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-coyote.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) [tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) [tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-12-01 08:39:42.351 ERROR [http-nio-8080-exec-6][PortletServlet:119] null
javax.portlet.PortletException: org.apache.thrift.TApplicationException: Internal error processing importAllOSADLLicenses
	at org.eclipse.sw360.portal.portlets.admin.LicenseAdminPortlet.serveResource(LicenseAdminPortlet.java:96) ~[bundleFile:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:146) ~[portal-impl.jar:?]
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:88) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:140) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:78) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:40) ~[?:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:566) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invokeResource(InvokerPortletImpl.java:681) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.serveResource(InvokerPortletImpl.java:494) ~[portal-impl.jar:?]
	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.serveResource(MonitoringInvokerPortlet.java:292) ~[?:?]
	at com.liferay.portlet.internal.PortletContainerImpl._serveResource(PortletContainerImpl.java:1072) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl.lambda$serveResource$4(PortletContainerImpl.java:267) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:421) [portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl.serveResource(PortletContainerImpl.java:260) [portal-impl.jar:?]
	at com.liferay.portlet.SecurityPortletContainerWrapper.serveResource(SecurityPortletContainerWrapper.java:199) [portal-impl.jar:?]
	at com.liferay.portlet.RestrictPortletContainerWrapper.serveResource(RestrictPortletContainerWrapper.java:150) [portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletContainerUtil.serveResource(PortletContainerUtil.java:232) [portal-kernel.jar:?]
	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:410) [portal-impl.jar:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:174) [portal-impl.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:395) [portal-impl.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:151) [portal-impl.jar:?]
	at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:208) [portal-impl.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) [servlet-api.jar:4.0.FR]
	at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:587) [portal-impl.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) [servlet-api.jar:4.0.FR]
	at com.liferay.shielded.container.internal.proxy.ServletWrapper.service(ServletWrapper.java:113) [com.liferay.shielded.container.impl.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) [catalina.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [catalina.jar:9.0.56]
	at org.apache.tomcat.websocket.server.WsFi [...]

2022-12-01 08:45 UTC, akapti commented
I will try to re-import by cleaning up all the existing obligations.

2022-12-01 09:51 UTC, merged

2022-12-06 21:43 UTC, dineshr93 commented
> Suggested couple of review comments.
> 
> Tested the changes and it's working as expected. here is the screenshot for reference: ![image](https://user-images.githubusercontent.com/50870174/204779052-b28aace1-87d3-43ca-bd17-6acec0afe8b2.png)
> 
> I suggest you to remove the usage of deprecated class `org.json.simple.JSONObject` in function `importAllOSADLLicenses` and use the new class `org.json.JSONObject`. You can use `length()` method instead of `org.json.simple.JSONObject` -> `size()` method wherever there are compile time error. (at line [969](https://github.com/eclipse/sw360/blob/main/backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java#L969))

<details>
<summary>Error log for missing obligations</summary>
```js

2022-12-06 20:13:35 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AAL.txt
2022-12-06 20:13:35 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:35 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/ADSL.txt
2022-12-06 20:13:35 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:35 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AFL-1.1.txt
2022-12-06 20:13:35 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:35 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AFL-1.2.txt
2022-12-06 20:13:35 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:38 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AGPL-1.0.txt
2022-12-06 20:13:38 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:38 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AGPL-1.0-only.txt
2022-12-06 20:13:38 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:38 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AGPL-1.0-or-later.txt
2022-12-06 20:13:38 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:38 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AGPL-3.0.txt
2022-12-06 20:13:38 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AMDPLPA.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AML.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/AMPAS.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/ANTLR-PD.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/APAFML.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/APL-1.0.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/APSL-1.0.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/APSL-1.1.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/APSL-1.2.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/APSL-2.0.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/Abstyles.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/Adobe-2006.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/Adobe-Glyph.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/Afmparse.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:45 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/Aladdin.txt
2022-12-06 20:13:45 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:53 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/Artistic-1.0-cl8.txt
2022-12-06 20:13:53 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:56 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-2-Clause-FreeBSD.txt
2022-12-06 20:13:56 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:56 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-2-Clause-NetBSD.txt
2022-12-06 20:13:56 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:57 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-3-Clause-Attribution.txt
2022-12-06 20:13:57 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:57 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-3-Clause-Clear.txt
2022-12-06 20:13:57 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:57 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-3-Clause-LBNL.txt
2022-12-06 20:13:57 ERROR OSADLObligationConnector:55 - HTTP Response Code: 404
2022-12-06 20:13:57 ERROR OSADLObligationConnector:54 - Could not open OSADL License URL: https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-3-Clause-No-Nuclear-License.txt
2022-12-06 20:13:57 ER [...]

2023-02-10 15:24 UTC, KoukiHama commented
@hoangnt2 @tienlee
Could you check #1809?