fix(UI):remove deactivated users from moderators list
eclipse/sw360 pull request #1761
Opened 2022-12-12 08:07 UTC by rudra-superrr

Signed-off-by: rudra-superrr <rudra.chopra@siemens.com>

Issue: #1758 

### How To Test?
- Create Moderation Request.
- After creating, check whether deactivated users are present in moderators list or not in Requests Portlet.

Run Script:
To remove deactivated users from the moderators list from database for old data.

2022-12-12 12:39 UTC, akapti requested changes
code looks good to me.
will approve the PR once testing is completed.

2022-12-12 12:39 UTC, akapti commented on scripts/migrations/054_remove_inactiveUsers_from_moderators.py
> +# This script is for changing the ecc status to Approved for the affected releases (releases with source code download url and component type OSS).
Kindly change the description of the script.

2022-12-12 12:52 UTC, akapti reviewed
changes looks good to me. will approve once PR is tested.

2022-12-20 10:13 UTC, nikkuma7 commented
Test successful.

2022-12-22 06:31 UTC, akapti approved these changes
@nikkuma7  has tested the PR, hence approving.

2023-01-09 09:21 UTC, merged