feat(Advance Search): Provided an 'Exact Match' checkbox in Advance Search that inserts (") around search keyword
eclipse/sw360 pull request #1781
Opened 2022-12-20 09:35 UTC by afsahsyeda

Signed-off-by: afsahsyeda <afsah.syeda@siemens-healhtineers.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

Description:
1) Exact Match checkbox has been provided in Projects, Components, Requests and 'Link Projects' and 'Link Releases' modal in Projects Portlet.
2) On being checked, it produces results exactly matching the search input.

Issue: #1757 

Screenshots:
![image](https://user-images.githubusercontent.com/115608771/208632864-b48509ce-e6da-41bf-98a1-3dde58c32585.png)
![image](https://user-images.githubusercontent.com/115608771/208633003-4769df2a-8590-43d2-919b-dedbf1fee953.png)

2022-12-21 07:57 UTC, nikkuma7 commented
Test successful.

2022-12-22 08:52 UTC, akapti requested changes
Kindly incorporate the suggested changes.

also noticed one minor issue, In `Advanced Search`, the checkbox is not getting checked when clicked on label `Exact Match`. The same is working fine in `linked project` and `linked release` search pop-up.

Sample screenshot:
![image](https://user-images.githubusercontent.com/50870174/209095724-36cfa15d-26d8-4360-9a2b-dee9a0b516f8.png)


Update: The checked status of checkbox is not being retained while performing Advanced search in `Project` and `Compoennts`

2023-01-10 09:26 UTC, akapti requested changes

2023-01-10 09:26 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
> +                    if(!exactMatch.isEmpty() && !(parameter.startsWith("\"") && parameter.endsWith("\""))) {
please maintain the correct formatting / intonation.
`if (` on line `1962` and `s -> "\"" + s + "\""` on line `1963`.

Kindly do the same change in `ProjectPortlet` and `ModerationPortlet` as well.

2023-01-10 09:26 UTC, akapti commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/components/ComponentPortlet.java
> +        response.setRenderParameter("exactMatchCheckBox", nullToEmpty(request.getParameter("exactMatchCheckBox")));
please create a constant in `PortalConstants.java` class and use it everywhere instead of `"exactMatchCheckBox"`.

2023-01-10 09:26 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/view.jsp
> +							<button type="submit" class="btn btn-primary btn-sm btn-block"><liferay-ui:message key="search" /></button>
correct the indentation.
also at line `155`.

2023-01-10 09:26 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/utils/includes/searchReleases.jsp
> +            if($('#exactMatchRelease').is(':checked') && !(searchRelease.startsWith("\"") && searchRelease.endsWith("\""))){
please correct the indentation.
`function() {` at line `95` and `if ($('#exactMatchRelease').is(':checked') && !(searchRelease.startsWith("\"") && searchRelease.endsWith("\""))) {`

also at line `48`.


please do the same change in `searchProjects.jsp` file as well.

2023-01-10 09:26 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/components/view.jsp
> +							<button type="submit" class="btn btn-primary btn-sm btn-block"><liferay-ui:message key="search" /></button>
correct the indentation.
also at line `174`.

2023-01-11 03:26 UTC, afsahsyeda commented
Hi @akapti ,

Please check now.

2023-01-12 08:50 UTC, akapti requested changes

2023-01-23 05:56 UTC, akapti approved these changes
code looks good.
tested the changes, working fine.

2023-01-23 09:01 UTC, merged