feat(Project): Added Vulnerability Summary Tab in Projects.
eclipse/sw360 pull request #1807
Opened 2023-01-16 07:58 UTC by rudra-superrr

Signed-off-by: rudra-superrr <rudra.chopra@siemens.com>

Issue: 

### How To Test?

2023-02-13 08:05 UTC, nikkuma7 commented
Test successful.

![image](https://user-images.githubusercontent.com/49710817/218403045-a98c9fc2-c274-4bbc-bd9d-cf5e6261c47e.png)
![image](https://user-images.githubusercontent.com/49710817/218403095-30beb079-61c9-4c50-a8cd-307c491c014a.png)
![image](https://user-images.githubusercontent.com/49710817/218403159-b35eee4a-fd8b-48f4-a738-0618b27038db.png)

2023-02-14 08:15 UTC, smrutis1 requested changes

2023-02-14 08:15 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +                List<String> ProjIds = links.stream().map(proj->proj.id).collect(Collectors.toList());
Please check the variable case.

2023-02-14 08:15 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +                for (int pos=0; pos<ProjIds.size(); pos++) {
indentation

2023-02-14 08:15 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/totalVulnerabilities.jsp
> +                	{ title: "<liferay-ui:message key="project.name" />"},
indentation

2023-02-14 08:15 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/totalVulnerabilities.jsp
> +  ~ Copyright Siemens AG, 2016-2017, 2019, 2021, 2023. Part of the SW360 Portal Project.
Please change the copyright

2023-02-14 09:24 UTC, rudra-superrr commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +                List<String> ProjIds = links.stream().map(proj->proj.id).collect(Collectors.toList());
made the changes

2023-02-14 09:24 UTC, rudra-superrr commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +                for (int pos=0; pos<ProjIds.size(); pos++) {
done

2023-02-14 09:24 UTC, rudra-superrr commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/totalVulnerabilities.jsp
> +                	{ title: "<liferay-ui:message key="project.name" />"},
done

2023-02-14 09:24 UTC, rudra-superrr commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/includes/projects/totalVulnerabilities.jsp
> +  ~ Copyright Siemens AG, 2016-2017, 2019, 2021, 2023. Part of the SW360 Portal Project.
done

2023-02-28 06:24 UTC, smrutis1 approved these changes
Code looks good

2023-02-28 11:45 UTC, merged