feat(ProjectsUI):Changed Expand All To Expand Next Level and added alert message
eclipse/sw360 pull request #1812
Opened 2023-01-19 05:29 UTC by afsahsyeda

Signed-off-by: afsahsyeda <afsah.syeda@siemens-healhtineers.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description:

- Expand All changed to 'Expand Next Level' to convey a clearer message as to how the nodes are loaded.
- An alert message saying 'All nodes are expanded!' is displayed after all the parent and child nodes are expanded successfully.

Issue: #1783 

### Suggest Reviewer
@akapti 

### How To Test?

1. Go to Projects portlet
2. Click on License Clearing tab
3. Click On 'Expand Next Level' button.

Screenshots:
![image](https://user-images.githubusercontent.com/115608771/213362050-73055f24-b115-414c-b8db-f9b0c62c145d.png)

2023-01-20 07:10 UTC, rudra-superrr commented
Hi @afsahsyeda ,
When you click Collapse all button in order to collapse the expanded result, it works fine. But if you again click on the Expand next level button, it will expand the result to the max level and it does not show the message(All the levels are expanded) i.e. it will not expand one level at a time.

![image](https://user-images.githubusercontent.com/58290634/213637756-bbea88ec-cd6d-4372-a273-c3265823b1a5.png)

2023-01-20 07:31 UTC, rudra-superrr commented
Testing was successful.

2023-01-23 07:26 UTC, smrutis1 approved these changes
Code looks good.

2023-01-23 09:12 UTC, akapti requested changes
kindly incorporate the review comments.

one possible issue I found while testing:
- Collapsing node of `AttachmentUsage` tree-table might hide the warning message in `License Clearing` tree view table.

2023-01-23 09:12 UTC, akapti commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/js/modules/ajax-treetable.js
> +                            if(nodeCount == Object.keys(node.tree).length){
please use correct indentation / formatting.
`if (condition) {` -> at line `52`, `43` and `29`.

2023-01-25 06:18 UTC, akapti approved these changes
LGTM.

2023-01-25 08:25 UTC, merged