feat(ui): Add banner to broadcast messages
eclipse/sw360 pull request #1830
Opened 2023-02-07 09:46 UTC by rudra-superrr

Signed-off-by: rchopra <rudra.chopra@siemens.com>

Issue: 

### How To Test?

2023-02-13 07:43 UTC, nikkuma7 commented
test successful.

![image](https://user-images.githubusercontent.com/49710817/218399061-72ceadd5-ad12-434e-a6ab-b4083509e2ee.png)

2023-02-13 11:11 UTC, akapti requested changes
please incorporate the review comment.

2023-02-13 11:11 UTC, akapti commented on frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
> +
Please remove this script tag, as banner JS has been removed. also at line `42` and `43`.

2023-02-13 12:43 UTC, akapti commented
One suggesting is to use the bootstrap `alert` CSS instead of creating own CSS for `updateMessage` div.

The message will look something like this if we user bootstrap `alert-info` class:
![image](https://user-images.githubusercontent.com/50870174/218460629-ac1789b8-cdaa-46e8-b426-91eef7df2caf.png)


in case we user `alert-warning` class:
![image](https://user-images.githubusercontent.com/50870174/218460445-3b035dd3-9ebb-4325-8bc3-afd40768bd6d.png)

2023-02-15 08:25 UTC, afsahsyeda commented
Hi @akapti ,

I have incorporated the changes. Please check.
![image](https://user-images.githubusercontent.com/115608771/218972411-45d6d9f9-c615-41a2-af8d-e1998b7e4228.png)

2023-02-15 09:17 UTC, akapti requested changes
please address review comment

2023-02-15 09:17 UTC, akapti commented on frontend/liferay-theme/src/main/webapp/templates/portal_normal.ftl
> +<#assign js_folder = theme_display.getPathThemeJavaScript() />
please remove this variable as it's never used.

2023-02-16 08:13 UTC, afsahsyeda commented
Hi @akapti ,
Please check now.

2023-02-16 08:49 UTC, akapti approved these changes
Looks good.

2023-02-16 08:53 UTC, merged