fix(ui): Fixed download license disclosure error upon selection of missing attchmnt
eclipse/sw360 pull request #951
Opened 2020-08-12 07:56 UTC by smrutis1

Signed-off-by: Smruti Sahoo <smruti.sahoo@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

This PR will validate the selected attachments in DB before downloading the license disclosure/project clearing report, accordingly it will show the warning message and an empty template will be downloaded.
There is no dependency changes. 

Issue: #950 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
Please refer issue #950 

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2020-08-12 08:48 UTC, mcjaeger commented
(from discussion) adding to the error message the attachment name would be good for the user (considering projects with 100s of components).

2020-08-19 07:31 UTC, smrutis1 commented
Thanks for the remarks. Have added the file names in the error message.

2020-08-20 07:12 UTC, JaideepPalit requested changes
**Reviewed and Tested the PR.** kindly look into some review comments and observed issues
**Issue 1 -**
Product clearing report give 500 white page error if attachment is missing.
![image](https://user-images.githubusercontent.com/56534710/90725540-f4be8d80-e2dd-11ea-82b4-65077e525603.png)

**Issue 2 -**
Generate ReadmeOSS with subproject - .html format with missing attachment - error message appears as expected.
Now unselect missing attachment , generate readmeoss in .txt or docx format - it generates readmeoss in html format.

2020-08-31 06:04 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/projects/licenseInfo.jsp
> +            }
I think it's okay to keep it as it is for readability purpose.

2020-08-31 06:06 UTC, smrutis1 commented on frontend/sw360-portlet/src/main/java/org/eclipse/sw360/portal/portlets/projects/ProjectPortlet.java
> +        AttachmentService.Iface attachmentClient = thriftClients.makeAttachmentClient();
I hope it's not in the context of this PR. would look good to do it in a independent PR as it might touch many files.?

2020-08-31 13:07 UTC, smrutis1 commented
Thanks @JaideepPalit . Have addressed most of the review comments.

2020-09-01 11:39 UTC, JaideepPalit requested changes
Tested the PR. Unfortunately some issues .
Issue 1 - Clearing report doesn't contain error msg, if attachment is missing. Error msg is shown in popup in UI only. For ReadmeOSS it appears in document as well as in popup
Issue 2 - 
 - Selected the missing attachment.
 - Exclude attachment by Filter Project-Release/Linked Project Relation
 - Expected behaviour download-ok, but shows error msg and empty ReadmeOSS/Report is downloaded

2020-09-07 03:43 UTC, smrutis1 commented
@JaideepPalit Have addressed the mentioned issues

2020-09-07 06:37 UTC, JaideepPalit approved these changes
Tested successfully

2020-09-07 06:38 UTC, merged