fix(license): Fixed the NullPointerException and addressed code duplication
eclipse/sw360 pull request #966
Opened 2020-09-01 05:24 UTC by smrutis1

Signed-off-by: Smruti Prakash Sahoo <smruti.sahoo@siemens.com>

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.

Ref Issue : #962 

Issue: 
Fixes #962 

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?

Try adding obligations in Admin -> Obligations view.
Download license archive from Admin -> Import & Export

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

2020-09-03 11:21 UTC, JaideepPalit requested changes
Code looks fine to me , except minor indentation issue. 
Tested successfully.

2020-09-03 11:21 UTC, JaideepPalit commented on backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
> +			}
Kindly check indentation

2020-09-07 03:02 UTC, smrutis1 commented on backend/src/src-licenses/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java
> +			}
Corrected.

2020-09-07 04:18 UTC, JaideepPalit approved these changes
Code looks good.

2020-09-07 04:20 UTC, merged