feat(CR-UI): Enhancement & Bug fixes
eclipse/sw360 pull request #976
Opened 2020-09-11 05:39 UTC by akapti

[//]: # (Copyright Bosch.IO GmbH 2020)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
* Which issue is this pull request belonging to and how is it solving it? -> Refer issue #972 
* Did you add or update any new dependencies that are required for your change? -> **NO**

### Suggest Reviewer
> You can suggest reviewers here with an @mention.

### How To Test?
* How should these changes be tested by the reviewer? -> Refer issue #972 
* Have you implemented any additional tests? -> **NO**

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

closes #972 

Signed-off-by: Abdul Kapti <abdul.mannankapti@siemens.com>

2020-10-01 10:52 UTC, JaideepPalit requested changes
Reviewed the PR, some minor review comments.
Need to test.

2020-10-01 10:52 UTC, JaideepPalit commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java
> +                .map(att -> new StringBuilder("\n\t").append(att.getFilename()).append(DatabaseHandlerUtil.SEPARATOR)
Use Platform-Independent Line Separators wherever possible.
`System.lineSeparator()`

2020-10-01 10:52 UTC, JaideepPalit commented on backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ProjectDatabaseHandler.java
> +        Integer count = 0;
Use `int` to prevent `Autoboxing` and `Unboxing` during increment and then convert it to string.

2020-10-01 10:52 UTC, JaideepPalit commented on backend/src-common/src/main/resources/RejectedCREmailemplate.html
> +	    Your clearing request with id: <b>%s</b> for the project: <b>%s</b> has been rejected by the clearing team.
looks same like `ClosedCREmailTemplate.html` . Could be merged using parameter for `rejected/closed`

2020-10-01 10:52 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/resources/content/Language.properties
> -components.to.be.cleared=Components to be cleared
Should be removed from `Language_ja.properties`

2020-10-01 10:52 UTC, JaideepPalit commented on libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/common/SW360Utils.java
> +                + clearingSummary.getSentToClearingTool()+ clearingSummary.getApproved();
indentation

2020-10-01 10:52 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
> +                        <select class="form-control form-control-sm" id="date_range" style="display: none;">
Bootstrap class can used here `d-none`

2020-10-01 10:52 UTC, JaideepPalit commented on frontend/sw360-portlet/src/main/resources/META-INF/resources/html/moderation/view.jsp
> +                    span.innerHTML = "P-3";
Should it be P-3 for all if - else cases?

2020-10-01 16:13 UTC, akapti commented
> Reviewed the PR, some minor review comments.
> Need to test.

Thanks, Incorporated review comments.

2020-10-06 08:02 UTC, JaideepPalit requested changes
Tested the PR. Kindly look into some minor issue observed during testing.

1. Bold text are not displayed as expected in `CR comment`, currently it appears as `<b>comment text</b>` instead of **comment text**.- `working fine`
2. `CR` breadcrumb in `CR Detail/Edit` page is redirecting to `Open Moderation Request` tab, It should redirect to `Open CR` tab or `Closed CR` tab (depending on status of CR). - seems to be some issue , it going to open mod req
3. `Requesting user` should be able to re-open the `closed` clearing request. - - `working fine` `Requesting user` along with `Clearing Team able to reopen request
4. Add a new `CR` status `ON_HOLD` with tool-tip: `Clearing Team is waiting for input/action from the Requesting User.` - `working fine`
5. Add `CR` progress bar in `Open CR` tab and in `Detail/Edit` page under `Clearing Decision` table.- `working fine`
   - Progress should be calculated based on Approved releases to Total release (directly linked to project).
   - Progress bar should be displayed only in `Open CR` tab, except the CR's in `NEW` status.
6. Creating a new `CR` should: - `working fine`
   - Add a new comment in CR, the comment will list all the linked release (Name & Id) with Clearing Status NEW.
   - Also mentioned the number of COTS components (linked release) in a CR.
   - The same information should be captured in Email being triggered when a new `CR` is created.
7. Updating (directly) `Linked Releases` of a `Project` (with CR) should:
   - Add a new comment in CR, listing all the `added` and `removed` linked releases.
   - An email should be triggering listing all the `linked releases` in `New` state and the number of `COTS` components in CR.
8. Please make `Agreed Clearing Date` non mandatory field while Editing `CR`.- `working fine`
9. Change Closed/Rejected `CR` email text, from `Approved` to `Closed` and `Declined` to `Rejected`. `working fine`
10. Re-opening `CR` should ask for new `Preferred Clearing Date` and keep track of `Re-opened` date. Display re-open count beside the re-open date in CR Details/Edit page. - `working fine`
11. Remove all the three date fields (`CR Creation Date`, `Preferred Clearing Date`, `Agreed Clearing Date`) from `Open CR` tab, and add filter w.r.t following dates:
     - `CR Creation Date`, `Preferred Clearing Date`, `Agreed Clearing Date`, and `Last updated Date`.
     - Add similar filter for `Closed CR` tab also, also include `CR closed on` date in filter.
     - Filter should have following options:
       - `today`, `Next 7 days`, `Next 30 days`, `Last 7 days`, `Last 30 days`.- `working fine` . May be for last updated on and created on - the greyed out options can be removed.
12. Add `CR-ID` & `Project Name` in subject of an email for `CR`. - `working fine`
13. Adding or Removing of `Attachments` from a directly linked `Release` in a `Project` should be reflected in `CR` comment.- `working fine`
14. Add `Priority` badge with typical sw360 color code beside `CR-ID` based on `Preferred clearing date`.
    - `P-0` badge if `Preferred clearing date` is within next 7 days.
    - `P-1` badge if `Preferred clearing date` is between next 7 to 14 days.
    - `P-2` badge if `Preferred clearing date` is between next 14 to 21 days.
    - `P-3` badge if `Preferred clearing date` is greater next 21 days.
  - Seems to be some issue P0 is not coming instead P1 is coming for next 7 days after that P2 ....

2020-10-07 08:55 UTC, akapti commented
> seems to be some issue , it going to open mod req 

Fixed the issue.

> Seems to be some issue P0 is not coming instead P1 is coming for next 7 days after that P2

not able to reproduce the issue.

2020-10-15 06:47 UTC, JaideepPalit commented
> > seems to be some issue , it going to open mod req
> 
> Fixed the issue.
>  - working fine

> > Seems to be some issue P0 is not coming instead P1 is coming for next 7 days after that P2
> 
> not able to reproduce the issue.
>  - looks like the earliest Preferred clearing date is coming to be after 7 days. Need to clarify. Maybe it can solved in a separate PR, if it is an issue
![image](https://user-images.githubusercontent.com/56534710/96086490-12743180-0ee0-11eb-96ee-afd367bf81ad.png)

2020-10-15 08:34 UTC, JaideepPalit approved these changes
(from discussion) - merging PR and create new issue after clarification.

2020-10-15 08:35 UTC, merged

2020-10-20 00:49 UTC, akapti commented
> looks like the earliest Preferred clearing date is coming to be after 7 days. 

Yes. that is expected behavior, The earliest `Preferred Clearing Date` should be greater than 7 days from the date on which `clearing request` is raised.