feat(ui): Allow access to merge/split of component and release based on user role configured in properties
eclipse/sw360 pull request #978
Opened 2020-09-11 11:21 UTC by JaideepPalit

> Allow access to merge/split of component and release based on user role configured in properties
> * Which issue is this pull request belonging to and how is it solving it? (*#977*)
> * Did you add or update any new dependencies that are required for your change? - No

### How To Test?
> Set value for `user.roles.allowed.to.merge.or.split.component` and validate user with those roles are able to merge or split component.
```
# Possible values are "Admin", "Clearing Admin", "Clearing Expert", "ECC Admin", "Security Admin", "SW360 Admin", "User"
# Admin by default has merge/split access
# It can be comma separated values , example - user.roles.allowed.to.merge.or.split.component=Clearing Admin,Clearing Expert
user.roles.allowed.to.merge.or.split.component= 
```
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2020-09-14 07:36 UTC, smrutis1 requested changes
I think, the comma separated roles will not work considering project permissions hierarchy

2020-09-23 11:38 UTC, JaideepPalit commented
(from discusssion)- It is ok to use `PermissionUtils.isUserAtLeast(UserGroup.ROLE, user)`, in order to maintain same behavior everywhere

2020-09-28 11:32 UTC, JaideepPalit commented
Changes done in order to maintain similar behavior everywhere

2020-09-30 13:41 UTC, smrutis1 commented
Tested successfully

2020-10-01 08:38 UTC, merged