fix(UserSearch): Fixed search user functionality
eclipse/sw360 pull request #994
Opened 2020-09-23 11:26 UTC by JaideepPalit

> Fixed search user functionality
> * Which issue is this pull request belonging to and how is it solving it? (*#991*)
> * Did you add or update any new dependencies that are required for your change? - No

### How To Test?
> - Goto Search Page - Search Project, Component, Release, User... 
> - Create/Edit Project, Component, Release - add user using search functionality to moderator, contributor, Project Responsible etc.
> Have you implemented any additional tests? - No

### Checklist
Must:
- [X] All related issues are referenced in commit messages and in PR

Signed-off-by: Jaideep Palit <jaideep.palit@siemens.com>

2020-09-24 22:08 UTC, mcjaeger commented
work on a staging instance for us.

2020-09-25 05:15 UTC, smrutis1 requested changes

2020-09-25 06:28 UTC, JaideepPalit commented on libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
> +        if (dbNameForLuceneSearch.equals(DatabaseSettings.COUCH_DB_USERS)) {
Changes done.

2020-09-25 06:28 UTC, JaideepPalit commented on libraries/lib-datahandler/src/main/java/org/eclipse/sw360/datahandler/couchdb/lucene/LuceneAwareDatabaseConnector.java
> +            else {
Changes done.

2020-09-25 07:58 UTC, smrutis1 approved these changes
Code looks good to me. Tested successfully again after recent changes in staging instance.

2020-09-25 08:13 UTC, merged